-- DROP SCHEMA dbo;

CREATE SCHEMA dbo;
-- PROJECT_ZERO.dbo.ACTIVITY_LOG definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.ACTIVITY_LOG;

CREATE TABLE PROJECT_ZERO.dbo.ACTIVITY_LOG (
	ACTIVITY_LOG_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	SYS_USER_ID numeric(18,0) NOT NULL,
	ACTIVITY_REMARKS nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DATE_TIME nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__ACTIVITY__CB0ACC226E441539 PRIMARY KEY (ACTIVITY_LOG_ID)
);


-- PROJECT_ZERO.dbo.DRIVERS definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.DRIVERS;

CREATE TABLE PROJECT_ZERO.dbo.DRIVERS (
	DRIVER_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	DRIVER_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DRIVER_LAST_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DRIVERS_NATIONAL_CODE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DRIVERS_PHONE_NUMBER nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	IS_DELETED bit NULL,
	FLEET_TEAM_ID numeric(18,0) NULL,
	CONSTRAINT PK__DRIVERS__030E1394EC67E358 PRIMARY KEY (DRIVER_ID),
	CONSTRAINT UQ_DRIVERS_NATIONAL_CODE UNIQUE (DRIVERS_NATIONAL_CODE),
	CONSTRAINT UQ_DRIVERS_PHONE UNIQUE (DRIVERS_PHONE_NUMBER)
);


-- PROJECT_ZERO.dbo.FLEET_TEAMS definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.FLEET_TEAMS;

CREATE TABLE PROJECT_ZERO.dbo.FLEET_TEAMS (
	FLEET_TEAM_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	FLEET_TEAM_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DESCRIPTION nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	IS_DELETED bit NULL,
	CONSTRAINT PK__FLEET_TE__906FB8ACBEDAF0F7 PRIMARY KEY (FLEET_TEAM_ID)
);


-- PROJECT_ZERO.dbo.INVENTORY_STOCK_REQUEST definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.INVENTORY_STOCK_REQUEST;

CREATE TABLE PROJECT_ZERO.dbo.INVENTORY_STOCK_REQUEST (
	INVENTORY_STOCK_REQUEST_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	INVENTORY_ID numeric(18,0) NULL,
	FROM_INVENTORY_ID numeric(18,0) NULL,
	PRODUCTS_ID numeric(18,0) NULL,
	IS_GET bit NULL,
	IS_DELETED bit NULL,
	PRODUCTS_COUNT numeric(18,0) NULL,
	ACCEPT_BY_INVENTORY_ID numeric(18,0) NULL,
	DRIVER_ID_ASSIGNED numeric(18,0) NULL,
	CONSTRAINT PK__INVENTOR__A4D2D9FDA25BE1CB PRIMARY KEY (INVENTORY_STOCK_REQUEST_ID)
);


-- PROJECT_ZERO.dbo.LT_INVENTORY_LOCATION_TYPE definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.LT_INVENTORY_LOCATION_TYPE;

CREATE TABLE PROJECT_ZERO.dbo.LT_INVENTORY_LOCATION_TYPE (
	LT_INVENTORY_LOCATION_TYPE_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	INVENTORY_LOCATION_TYPE_TITLE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IS_DELETED bit NULL,
	CONSTRAINT PK__LT_INVEN__8701A02787ECB33A PRIMARY KEY (LT_INVENTORY_LOCATION_TYPE_ID)
);


-- PROJECT_ZERO.dbo.LT_ROLES definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.LT_ROLES;

CREATE TABLE PROJECT_ZERO.dbo.LT_ROLES (
	ROLES_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	ROLE_CODE numeric(18,0) NOT NULL,
	ROLES_TITLE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK__LT_ROLES__A24FBB16DE01410D PRIMARY KEY (ROLES_ID),
	CONSTRAINT UQ__LT_ROLES__20BB649DA1B5E8E4 UNIQUE (ROLE_CODE),
	CONSTRAINT UQ__LT_ROLES__676386A8B59F4AF1 UNIQUE (ROLES_TITLE)
);


-- PROJECT_ZERO.dbo.PRODUCTS_CATEGORY definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.PRODUCTS_CATEGORY;

CREATE TABLE PROJECT_ZERO.dbo.PRODUCTS_CATEGORY (
	PRODUCTS_CATEGORY_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	PRODUCTS_CATEGORY_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IS_DELETED bit NULL,
	CONSTRAINT PK__PRODUCTS__F1C1E23B2B52B202 PRIMARY KEY (PRODUCTS_CATEGORY_ID)
);


-- PROJECT_ZERO.dbo.SYS_CALL_ACCESS definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.SYS_CALL_ACCESS;

CREATE TABLE PROJECT_ZERO.dbo.SYS_CALL_ACCESS (
	SYS_CALL_ACCESS_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	ROLE_CODE numeric(18,0) NULL,
	CAN_READ bit NULL,
	CAN_WRITE bit NULL,
	SYS_OBJECT_CODE numeric(18,0) NULL,
	CONSTRAINT PK__SYS_CALL__1C5DECD0FC7E5667 PRIMARY KEY (SYS_CALL_ACCESS_ID)
);


-- PROJECT_ZERO.dbo.SYS_OBJECTS definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.SYS_OBJECTS;

CREATE TABLE PROJECT_ZERO.dbo.SYS_OBJECTS (
	SYS_OBJECT_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	SYS_OBJECT_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SYS_OBJECT_CODE numeric(18,0) NOT NULL,
	CONSTRAINT PK__SYS_OBJE__0F9D6F19F8515390 PRIMARY KEY (SYS_OBJECT_ID)
);


-- PROJECT_ZERO.dbo.SYS_USERS definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.SYS_USERS;

CREATE TABLE PROJECT_ZERO.dbo.SYS_USERS (
	SYS_USER_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	USERNAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	USER_PASSWORD varbinary(512) NOT NULL,
	LOGIN_SESSION nvarchar(512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BASE_SALARY decimal(6,1) NULL,
	CONSTRAINT PK__SYS_USER__2B4E4E5C292644C2 PRIMARY KEY (SYS_USER_ID)
);


-- PROJECT_ZERO.dbo.TASKS definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.TASKS;

CREATE TABLE PROJECT_ZERO.dbo.TASKS (
	TASKS_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	TASK_NAME nvarchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TASK_DESCRIPTION nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TASK_FOR_ROLE_ID numeric(18,0) NULL,
	START_DATE_TIME nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	END_DATE_TIME nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACCEPTED_BY_SYS_USER_ID numeric(18,0) NULL,
	EST_HOURS_IT_WILL_TAKE decimal(6,2) NULL,
	ACTUAL_TIME_TASK_TOOK decimal(6,2) NULL,
	HOURLY_RATE_FOR_TASK decimal(6,2) NULL,
	TASK_CREATED_BY_SYS_USER_ID numeric(18,0) NOT NULL,
	CREATED_DATE nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IS_DELETED bit DEFAULT 0 NOT NULL,
	CONSTRAINT PK__TASKS__A00C07A49D8AAB71 PRIMARY KEY (TASKS_ID)
);
ALTER TABLE PROJECT_ZERO.dbo.TASKS WITH NOCHECK ADD CONSTRAINT CK__TASKS__ACTUAL_TI__5FB337D6 CHECK (([ACTUAL_TIME_TASK_TOOK]>(0)));
ALTER TABLE PROJECT_ZERO.dbo.TASKS WITH NOCHECK ADD CONSTRAINT CK__TASKS__EST_HOURS__60A75C0F CHECK (([EST_HOURS_IT_WILL_TAKE]>(0)));
ALTER TABLE PROJECT_ZERO.dbo.TASKS WITH NOCHECK ADD CONSTRAINT CK__TASKS__HOURLY_RA__619B8048 CHECK (([HOURLY_RATE_FOR_TASK]>(0)));


-- PROJECT_ZERO.dbo.USERS_ROLES definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.USERS_ROLES;

CREATE TABLE PROJECT_ZERO.dbo.USERS_ROLES (
	USERS_ROLES_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	SYS_USER_ID numeric(18,0) NOT NULL,
	ROLE_CODE numeric(18,0) NOT NULL,
	ASSIGNMENT_DATE nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REVOKE_DATE nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IS_ACTIVE bit NULL,
	CONSTRAINT PK__USERS_RO__DEA33A14CA6A7459 PRIMARY KEY (USERS_ROLES_ID),
	CONSTRAINT UQ_USERS_ROLES_USER_ROLE UNIQUE (SYS_USER_ID,ROLE_CODE)
);


-- PROJECT_ZERO.dbo.USER_LOGIN_LOG definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.USER_LOGIN_LOG;

CREATE TABLE PROJECT_ZERO.dbo.USER_LOGIN_LOG (
	USER_LOGIN_LOG_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	SYS_USER_ID numeric(18,0) NOT NULL,
	LOGIN_DATE nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK__USER_LOG__437C1838A9454AE3 PRIMARY KEY (USER_LOGIN_LOG_ID)
);


-- PROJECT_ZERO.dbo.USER_OWNER_SHIP definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.USER_OWNER_SHIP;

CREATE TABLE PROJECT_ZERO.dbo.USER_OWNER_SHIP (
	USER_OWNER_SHIP_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	SYS_USER_ID numeric(18,0) NOT NULL,
	INVENTORY_ID numeric(18,0) NULL,
	FLEET_ID numeric(18,0) NULL,
	CONSTRAINT PK__USER_OWN__22D692798EDB8780 PRIMARY KEY (USER_OWNER_SHIP_ID)
);


-- PROJECT_ZERO.dbo.VEHICLE definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.VEHICLE;

CREATE TABLE PROJECT_ZERO.dbo.VEHICLE (
	VEHICLE_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	VEHICLE_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	VEHICLE_LICENCE_PLATE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	IS_DELETED bit NULL,
	CONSTRAINT PK__VEHICLE__7F2CA3502CF00E2C PRIMARY KEY (VEHICLE_ID)
);


-- PROJECT_ZERO.dbo.WORK_HOUR_REPORT_LOG definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.WORK_HOUR_REPORT_LOG;

CREATE TABLE PROJECT_ZERO.dbo.WORK_HOUR_REPORT_LOG (
	WORK_HOUR_REPORT_LOG_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	SYS_USER_ID numeric(18,0) NOT NULL,
	COMPLETED_TASK_ID numeric(18,0) NULL,
	CONSTRAINT PK__WORK_HOU__A4E7734807B0CE13 PRIMARY KEY (WORK_HOUR_REPORT_LOG_ID)
);


-- PROJECT_ZERO.dbo.INVENTORY_LOCATION definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.INVENTORY_LOCATION;

CREATE TABLE PROJECT_ZERO.dbo.INVENTORY_LOCATION (
	INVENTORY_LOCATION_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	INVENTORY_LOCATION_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INVENTORY_LOCATION_ADDRESS nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	INVENTORY_LOCATION_LAT decimal(9,6) NOT NULL,
	INVENTORY_LOCATION_LONG decimal(9,6) NOT NULL,
	LT_INVENTORY_LOCATION_TYPE_ID numeric(18,0) NOT NULL,
	IS_DELETED bit NULL,
	CONSTRAINT PK__INVENTOR__725D6AEFDB040A7E PRIMARY KEY (INVENTORY_LOCATION_ID),
	CONSTRAINT UQ_INVENTORY_LOCATION UNIQUE (INVENTORY_LOCATION_NAME,INVENTORY_LOCATION_ADDRESS,INVENTORY_LOCATION_LAT,INVENTORY_LOCATION_LONG),
	CONSTRAINT FK__INVENTORY__LT_IN__0C85DE4D FOREIGN KEY (LT_INVENTORY_LOCATION_TYPE_ID) REFERENCES PROJECT_ZERO.dbo.LT_INVENTORY_LOCATION_TYPE(LT_INVENTORY_LOCATION_TYPE_ID)
);


-- PROJECT_ZERO.dbo.PRODUCTS definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.PRODUCTS;

CREATE TABLE PROJECT_ZERO.dbo.PRODUCTS (
	PRODUCTS_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	PRODUCTS_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PRODUCTS_CATEGORY_ID numeric(18,0) NULL,
	IS_DELETED bit NULL,
	CONSTRAINT PK__PRODUCTS__3F2458C776019CD0 PRIMARY KEY (PRODUCTS_ID),
	CONSTRAINT FK__PRODUCTS__PRODUC__06CD04F7 FOREIGN KEY (PRODUCTS_CATEGORY_ID) REFERENCES PROJECT_ZERO.dbo.PRODUCTS_CATEGORY(PRODUCTS_CATEGORY_ID)
);


-- PROJECT_ZERO.dbo.PRODUCTS_MOVEMENTS definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.PRODUCTS_MOVEMENTS;

CREATE TABLE PROJECT_ZERO.dbo.PRODUCTS_MOVEMENTS (
	PRODUCTS_MOVEMENTS_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	DRIVERS_ID numeric(18,0) NOT NULL,
	VEHICLE_ID numeric(18,0) NOT NULL,
	COMES_FROM_LOCATION_ID numeric(18,0) NOT NULL,
	GOES_TO_LOCATION_ID numeric(18,0) NOT NULL,
	START_DATE_HOUR nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	END_DATE_HOUR nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EST_ARIVAL nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DID_ARIVE bit NULL,
	IS_DELETED bit NULL,
	IS_ACTIVE bit NULL,
	GOES_TO_LOCATION_ID_l nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__PRODUCTS__077925396FDD356B PRIMARY KEY (PRODUCTS_MOVEMENTS_ID),
	CONSTRAINT FK__PRODUCTS___COMES__1AD3FDA4 FOREIGN KEY (COMES_FROM_LOCATION_ID) REFERENCES PROJECT_ZERO.dbo.INVENTORY_LOCATION(INVENTORY_LOCATION_ID),
	CONSTRAINT FK__PRODUCTS___DRIVE__18EBB532 FOREIGN KEY (DRIVERS_ID) REFERENCES PROJECT_ZERO.dbo.DRIVERS(DRIVER_ID),
	CONSTRAINT FK__PRODUCTS___GOES___1BC821DD FOREIGN KEY (GOES_TO_LOCATION_ID) REFERENCES PROJECT_ZERO.dbo.INVENTORY_LOCATION(INVENTORY_LOCATION_ID),
	CONSTRAINT FK__PRODUCTS___VEHIC__19DFD96B FOREIGN KEY (VEHICLE_ID) REFERENCES PROJECT_ZERO.dbo.VEHICLE(VEHICLE_ID)
);


-- PROJECT_ZERO.dbo.PRODUCTS_STOCKS definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.PRODUCTS_STOCKS;

CREATE TABLE PROJECT_ZERO.dbo.PRODUCTS_STOCKS (
	PRODUCTS_STOCKS_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	PRODUCTS_ID numeric(18,0) NOT NULL,
	INVENTORY_LOCATION_ID numeric(18,0) NOT NULL,
	PRODUCT_COUNT_IN_STOCK numeric(18,0) NULL,
	CONSTRAINT PK__PRODUCTS__00BE76EAC838822B PRIMARY KEY (PRODUCTS_STOCKS_ID),
	CONSTRAINT UQ_PRODUCT_LOCATION UNIQUE (PRODUCTS_ID,INVENTORY_LOCATION_ID),
	CONSTRAINT FK__PRODUCTS___INVEN__114A936A FOREIGN KEY (INVENTORY_LOCATION_ID) REFERENCES PROJECT_ZERO.dbo.INVENTORY_LOCATION(INVENTORY_LOCATION_ID),
	CONSTRAINT FK__PRODUCTS___PRODU__10566F31 FOREIGN KEY (PRODUCTS_ID) REFERENCES PROJECT_ZERO.dbo.PRODUCTS(PRODUCTS_ID)
);
ALTER TABLE PROJECT_ZERO.dbo.PRODUCTS_STOCKS WITH NOCHECK ADD CONSTRAINT CK__PRODUCTS___PRODU__123EB7A3 CHECK (([PRODUCT_COUNT_IN_STOCK]>=(0)));


-- PROJECT_ZERO.dbo.MOVEMENTS_PRODUCTS_LIST definition

-- Drop table

-- DROP TABLE PROJECT_ZERO.dbo.MOVEMENTS_PRODUCTS_LIST;

CREATE TABLE PROJECT_ZERO.dbo.MOVEMENTS_PRODUCTS_LIST (
	MOVEMENTS_PRODUCTS_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
	MOVEMENTS_ID numeric(18,0) NOT NULL,
	PRODUCTS_ID numeric(18,0) NOT NULL,
	PRODUCTS_COUNT numeric(18,0) NULL,
	CONSTRAINT PK__MOVEMENT__15D0A82D5D055CBE PRIMARY KEY (MOVEMENTS_PRODUCTS_ID),
	CONSTRAINT FK__MOVEMENTS__MOVEM__1EA48E88 FOREIGN KEY (MOVEMENTS_ID) REFERENCES PROJECT_ZERO.dbo.PRODUCTS_MOVEMENTS(PRODUCTS_MOVEMENTS_ID),
	CONSTRAINT FK__MOVEMENTS__PRODU__1F98B2C1 FOREIGN KEY (PRODUCTS_ID) REFERENCES PROJECT_ZERO.dbo.PRODUCTS(PRODUCTS_ID)
);
ALTER TABLE PROJECT_ZERO.dbo.MOVEMENTS_PRODUCTS_LIST WITH NOCHECK ADD CONSTRAINT CK__MOVEMENTS__PRODU__208CD6FA CHECK (([PRODUCTS_COUNT]>(0)));



CREATE   PROCEDURE [dbo].[ACTIVITY_LOG_MANAGER]
@READ_ONLY BIT = 1
,@LOGGIN_SESSION NVARCHAR(512) = NULL
,@ACTIVITY_REMARK NVARCHAR(300) = NULL
AS
BEGIN

	DECLARE @SYS_USER_ID NUMERIC = (SELECT TOP 1 SYS_USER_ID FROM SYS_USERS WHERE LOGIN_SESSION = @LOGGIN_SESSION)

	IF @READ_ONLY = 0
	BEGIN
		
		INSERT INTO ACTIVITY_LOG
		(
		SYS_USER_ID,
		ACTIVITY_REMARKS,
		DATE_TIME
		)
		VALUES
		(
		@SYS_USER_ID,
		@ACTIVITY_REMARK,
		CONVERT(NVARCHAR(19), GETDATE(), 120)
		)
		SELECT 1 AS STATUS
	END
	ELSE
	BEGIN

		SELECT ACTIVITY_LOG_ID, AL.SYS_USER_ID, USERNAME, AL.ACTIVITY_REMARKS, DATE_TIME FROM ACTIVITY_LOG AL INNER JOIN SYS_USERS SU ON AL.SYS_USER_ID = SU.SYS_USER_ID 

	END
END;

CREATE   PROCEDURE [dbo].[CHANGE_PASSWORD]
@NEW_PASSWORD NVARCHAR(50),
@OLD_PASSWORD NVARCHAR(50),
@LOGIN_SESSION NVARCHAR(512)
AS
BEGIN
	IF EXISTS(SELECT 1 FROM SYS_USERS WHERE LOGIN_SESSION = @LOGIN_SESSION AND USER_PASSWORD = HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @OLD_PASSWORD, N'4THEYS123#AYIMJO31SEPHSEED')))
	BEGIN
		UPDATE SYS_USERS
		SET
		USER_PASSWORD = HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @NEW_PASSWORD, N'4THEYS123#AYIMJO31SEPHSEED'))
		WHERE LOGIN_SESSION = @LOGIN_SESSION
		SELECT 1 AS STATUS
		EXEC ACTIVITY_LOG_MANAGER 0, @LOGIN_SESSION, N'USER SUCCESSFULLY CHANGED PASSWORD'
	END
	ELSE
	BEGIN
	SELECT 0 AS STATUS
		EXEC ACTIVITY_LOG_MANAGER 0, @LOGIN_SESSION, N'USER TRIED AND FAILED TO CHANGE PASSWORD'
	END
END;

CREATE   PROCEDURE [dbo].[CHANGE_USER_CRED_BY_ADMIN]
@SYS_USER_ID NUMERIC,
@CHANGE_PASSWORD BIT,
@CHANGED_DATA NVARCHAR(100)
AS
BEGIN

	IF @CHANGE_PASSWORD = 1
		BEGIN
			UPDATE SYS_USERS 
			SET 
			USER_PASSWORD = HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @CHANGED_DATA, N'4THEYS123#AYIMJO31SEPHSEED'))
			WHERE SYS_USER_ID = @SYS_USER_ID
		END
	ELSE
		BEGIN
			UPDATE SYS_USERS 
			SET 
			USERNAME = @CHANGED_DATA
			WHERE SYS_USER_ID = @SYS_USER_ID
		END
		SELECT 1 AS STATUS
END;

CREATE   PROCEDURE [dbo].[CHANGE_USERNAME]
@NEW_USERNAME NVARCHAR(50),
@LOGIN_SESSION NVARCHAR(512)
AS
BEGIN
	UPDATE SYS_USERS SET USERNAME = @NEW_USERNAME WHERE LOGIN_SESSION = @LOGIN_SESSION
	EXEC ACTIVITY_LOG_MANAGER 0, @LOGIN_SESSION, N'USER SUCCESSFULLY CHANGED THEIR USERNAME'
	SELECT 1 AS STATUS
END;

CREATE    PROCEDURE CREATE_UPDATE_DELETE_DRIVER
    @ACTION                NVARCHAR(50),
    @DRIVER_ID             NUMERIC      = NULL,
    @DRIVER_NAME           NVARCHAR(50) = NULL,
    @DRIVER_LAST_NAME      NVARCHAR(50) = NULL,
    @DRIVERS_NATIONAL_CODE NVARCHAR(50) = NULL,
    @DRIVERS_PHONE_NUMBER  NVARCHAR(50) = NULL
AS
BEGIN
	SET NOCOUNT ON;
    SET @ACTION = UPPER(@ACTION);

    -- CREATE or RESTORE a driver
    IF @ACTION = N'CREATE_DRIVER'
    AND @DRIVER_NAME IS NOT NULL
	AND @DRIVER_LAST_NAME IS NOT NULL
	AND @DRIVERS_NATIONAL_CODE IS NOT NULL
	AND @DRIVERS_PHONE_NUMBER IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM DRIVERS
                       WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE)
            INSERT INTO DRIVERS (DRIVER_NAME, DRIVER_LAST_NAME,
                                DRIVERS_NATIONAL_CODE, DRIVERS_PHONE_NUMBER)
            VALUES (@DRIVER_NAME, @DRIVER_LAST_NAME,
                    @DRIVERS_NATIONAL_CODE, @DRIVERS_PHONE_NUMBER);
        ELSE
            UPDATE DRIVERS
			SET
			    IS_DELETED = 0,
			    DRIVER_NAME = @DRIVER_NAME,
			    DRIVER_LAST_NAME = @DRIVER_LAST_NAME,
			    DRIVERS_PHONE_NUMBER = @DRIVERS_PHONE_NUMBER
			WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE;
    END

    -- UPDATE an existing driver by ID
    IF @ACTION = N'UPDATE_DRIVER'
       AND @DRIVER_ID IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM DRIVERS WHERE DRIVER_ID = @DRIVER_ID)
            UPDATE DRIVERS
            SET DRIVER_NAME           = ISNULL(@DRIVER_NAME, DRIVER_NAME),
                DRIVER_LAST_NAME      = ISNULL(@DRIVER_LAST_NAME, DRIVER_LAST_NAME),
                DRIVERS_NATIONAL_CODE = ISNULL(@DRIVERS_NATIONAL_CODE, DRIVERS_NATIONAL_CODE),
                DRIVERS_PHONE_NUMBER  = ISNULL(@DRIVERS_PHONE_NUMBER, DRIVERS_PHONE_NUMBER)
            WHERE DRIVER_ID = @DRIVER_ID;
    END

    -- SOFT DELETE a driver by ID
    IF @ACTION = N'DELETE_DRIVER'
       AND @DRIVER_ID IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM DRIVERS WHERE DRIVER_ID = @DRIVER_ID)
            UPDATE DRIVERS
            SET IS_DELETED = 1
            WHERE DRIVER_ID = @DRIVER_ID;
    END
    SELECT 1
END;

CREATE    PROCEDURE CREATE_UPDATE_DELETE_INVENTORY_LOCATION
    @ACTION                        NVARCHAR(50),
    @INVENTORY_LOCATION_ID         NUMERIC      = NULL,
    @INVENTORY_LOCATION_NAME       NVARCHAR(50) = NULL,
    @INVENTORY_LOCATION_ADDRESS    NVARCHAR(300) = NULL,
    @INVENTORY_LOCATION_LAT        DECIMAL(9, 6) = NULL,
    @INVENTORY_LOCATION_LONG       DECIMAL(9, 6) = NULL,
    @LT_INVENTORY_LOCATION_TYPE_ID NUMERIC      = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET @ACTION = UPPER(@ACTION);

    -- CREATE or RESTORE a location
    IF @ACTION = N'CREATE_INVENTORY_LOCATION'
       AND @INVENTORY_LOCATION_NAME IS NOT NULL
       AND @INVENTORY_LOCATION_ADDRESS IS NOT NULL
       AND @INVENTORY_LOCATION_LAT IS NOT NULL
       AND @INVENTORY_LOCATION_LONG IS NOT NULL
       AND @LT_INVENTORY_LOCATION_TYPE_ID IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM INVENTORY_LOCATION
                       WHERE INVENTORY_LOCATION_NAME = @INVENTORY_LOCATION_NAME
		               AND INVENTORY_LOCATION_ADDRESS = @INVENTORY_LOCATION_ADDRESS
		    	 	   AND INVENTORY_LOCATION_LAT = @INVENTORY_LOCATION_LAT
		    	 	   AND INVENTORY_LOCATION_LONG = @INVENTORY_LOCATION_LONG)
            INSERT INTO INVENTORY_LOCATION
                (INVENTORY_LOCATION_NAME, INVENTORY_LOCATION_ADDRESS,
                 INVENTORY_LOCATION_LAT, INVENTORY_LOCATION_LONG,
                 LT_INVENTORY_LOCATION_TYPE_ID)
            VALUES
                (@INVENTORY_LOCATION_NAME, @INVENTORY_LOCATION_ADDRESS,
                 @INVENTORY_LOCATION_LAT, @INVENTORY_LOCATION_LONG,
                 @LT_INVENTORY_LOCATION_TYPE_ID);
        ELSE
            UPDATE INVENTORY_LOCATION
            SET
                IS_DELETED = 0,
                INVENTORY_LOCATION_NAME = @INVENTORY_LOCATION_NAME,
                INVENTORY_LOCATION_ADDRESS = @INVENTORY_LOCATION_ADDRESS,
                INVENTORY_LOCATION_LAT = @INVENTORY_LOCATION_LAT,
                INVENTORY_LOCATION_LONG = @INVENTORY_LOCATION_LONG,
                LT_INVENTORY_LOCATION_TYPE_ID = @LT_INVENTORY_LOCATION_TYPE_ID
            WHERE INVENTORY_LOCATION_NAME = @INVENTORY_LOCATION_NAME
              AND INVENTORY_LOCATION_ADDRESS = @INVENTORY_LOCATION_ADDRESS
    		  AND INVENTORY_LOCATION_LAT = @INVENTORY_LOCATION_LAT
    		  AND INVENTORY_LOCATION_LONG = @INVENTORY_LOCATION_LONG;
    END

    -- UPDATE an existing location by ID
    IF @ACTION = N'UPDATE_INVENTORY_LOCATION'
       AND @INVENTORY_LOCATION_ID IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM INVENTORY_LOCATION
                   WHERE INVENTORY_LOCATION_ID = @INVENTORY_LOCATION_ID)
            UPDATE INVENTORY_LOCATION
            SET
                INVENTORY_LOCATION_NAME       = ISNULL(@INVENTORY_LOCATION_NAME, INVENTORY_LOCATION_NAME),
                INVENTORY_LOCATION_ADDRESS    = ISNULL(@INVENTORY_LOCATION_ADDRESS, INVENTORY_LOCATION_ADDRESS),
                INVENTORY_LOCATION_LAT        = ISNULL(@INVENTORY_LOCATION_LAT, INVENTORY_LOCATION_LAT),
                INVENTORY_LOCATION_LONG       = ISNULL(@INVENTORY_LOCATION_LONG, INVENTORY_LOCATION_LONG),
                LT_INVENTORY_LOCATION_TYPE_ID = ISNULL(@LT_INVENTORY_LOCATION_TYPE_ID, LT_INVENTORY_LOCATION_TYPE_ID)
            WHERE INVENTORY_LOCATION_ID = @INVENTORY_LOCATION_ID;
    END

    -- SOFT DELETE a location by ID
    IF @ACTION = N'DELETE_INVENTORY_LOCATION'
       AND @INVENTORY_LOCATION_ID IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM INVENTORY_LOCATION
                   WHERE INVENTORY_LOCATION_ID = @INVENTORY_LOCATION_ID)
            UPDATE INVENTORY_LOCATION
            SET IS_DELETED = 1
            WHERE INVENTORY_LOCATION_ID = @INVENTORY_LOCATION_ID;
    END
    SELECT 1
END;

CREATE   PROCEDURE [dbo].[CREATE_UPDATE_DELETE_ROLES]
@ACTION_NAME NVARCHAR(20),
@ROLE_CODE NUMERIC = 0,
@ROLE_NAME NVARCHAR(50) = NULL,
@SYS_OBJECT_NAME NVARCHAR(50) = NULL,
@CAN_READ BIT = 0,
@CAN_WRITE BIT = 0
AS
BEGIN
DECLARE @OBJECT_CODE NUMERIC = (SELECT TOP 1 SYS_OBJECT_CODE FROM SYS_OBJECTS WHERE SYS_OBJECT_NAME = @SYS_OBJECT_NAME)
	IF LOWER(@ACTION_NAME) = LOWER(N'DELETE_ROLE') AND NOT @ROLE_CODE = 0
		BEGIN
			DELETE FROM SYS_CALL_ACCESS WHERE ROLE_CODE = @ROLE_CODE
			DELETE FROM LT_ROLES WHERE ROLE_CODE = @ROLE_CODE
		END
	ELSE IF LOWER(@ACTION_NAME) = LOWER(N'CREATE_ROLE') AND @ROLE_NAME IS NOT NULL
			AND NOT EXISTS(SELECT 1 FROM LT_ROLES WHERE ROLE_CODE = @ROLE_CODE)
		BEGIN
			INSERT INTO LT_ROLES (ROLE_CODE, ROLES_TITLE) VALUES (@ROLE_CODE, @ROLE_NAME)
		END
	ELSE IF LOWER(@ACTION_NAME) = LOWER(N'UPDATE_ROLE') AND NOT @ROLE_CODE = 0
		BEGIN
			UPDATE LT_ROLES SET ROLES_TITLE = @ROLE_NAME WHERE ROLE_CODE = @ROLE_CODE
		END
	ELSE IF LOWER(@ACTION_NAME) = LOWER(N'ADD_PERMISSION') AND NOT @ROLE_CODE = 0 AND @SYS_OBJECT_NAME IS NOT NULL
			AND EXISTS(SELECT TOP 1 1 FROM SYS_OBJECTS WHERE SYS_OBJECT_NAME = @SYS_OBJECT_NAME)
			AND EXISTS(SELECT TOP 1 1 FROM LT_ROLES WHERE ROLE_CODE = @ROLE_CODE)
		BEGIN
			IF NOT EXISTS(SELECT 1 FROM SYS_CALL_ACCESS WHERE SYS_OBJECT_CODE = @OBJECT_CODE AND ROLE_CODE = @ROLE_CODE)
				BEGIN
					INSERT INTO SYS_CALL_ACCESS (ROLE_CODE, SYS_OBJECT_CODE, CAN_READ, CAN_WRITE) VALUES (@ROLE_CODE, @OBJECT_CODE, @CAN_READ, @CAN_WRITE)
				END
			ELSE
				BEGIN
					UPDATE SYS_CALL_ACCESS
					SET
						CAN_READ = @CAN_READ,
						CAN_WRITE = @CAN_WRITE
						WHERE SYS_OBJECT_CODE = @OBJECT_CODE AND ROLE_CODE = @ROLE_CODE
				END
		END
	ELSE IF LOWER(@ACTION_NAME) = LOWER(N'DELETE_PERMISSION') AND NOT @ROLE_CODE = 0 AND @SYS_OBJECT_NAME IS NOT NULL
		BEGIN
			DELETE FROM SYS_CALL_ACCESS WHERE SYS_OBJECT_CODE = @OBJECT_CODE AND ROLE_CODE = @ROLE_CODE
		END

	SELECT 1 AS STATUS
END;

CREATE   PROCEDURE CREATE_UPDATE_DELETE_TASK
    @ACTION                NVARCHAR(50),
    @USER_ID               NUMERIC        = NULL,
    @TASK_ID               NUMERIC        = NULL,
    @TASK_NAME             NVARCHAR(50)   = NULL,
    @TASK_DESC             NVARCHAR(100)  = NULL,
    @TASK_FOR_ROLE_ID      NUMERIC        = NULL,
    @EST_HOURS_IT_TAKES    DECIMAL(6,2)   = NULL,
    @HOURLY_PAYMENT_RATE   DECIMAL(6,2)   = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET @ACTION = UPPER(@ACTION);

    -- =========================================================
    -- CREATE or RESTORE a task (soft‑delete reversal)
    -- =========================================================
    IF @ACTION = N'CREATE_TASK'
       AND @TASK_NAME IS NOT NULL
       AND @TASK_DESC IS NOT NULL
       AND @TASK_FOR_ROLE_ID IS NOT NULL
       AND @EST_HOURS_IT_TAKES IS NOT NULL
       AND @HOURLY_PAYMENT_RATE IS NOT NULL
       AND @USER_ID IS NOT NULL
    BEGIN
        -- Uniqueness check on (NAME, DESCRIPTION, ROLE)
        IF NOT EXISTS (
            SELECT 1 FROM PROJECT_ZERO.dbo.TASKS
            WHERE TASK_NAME        = @TASK_NAME
              AND TASK_DESCRIPTION = @TASK_DESC
              AND TASK_FOR_ROLE_ID = @TASK_FOR_ROLE_ID
        )
            INSERT INTO PROJECT_ZERO.dbo.TASKS
            (
                TASK_NAME,
                TASK_DESCRIPTION,
                TASK_FOR_ROLE_ID,
                EST_HOURS_IT_WILL_TAKE,
                HOURLY_RATE_FOR_TASK,
                TASK_CREATED_BY_SYS_USER_ID,
                CREATED_DATE
            )
            VALUES
            (
                @TASK_NAME,
                @TASK_DESC,
                @TASK_FOR_ROLE_ID,
                @EST_HOURS_IT_TAKES,
                @HOURLY_PAYMENT_RATE,
                @USER_ID,
                CONVERT(NVARCHAR(19), GETDATE(), 120)
            );
        ELSE
            -- Restore the existing (soft‑deleted) record and refresh its data
            UPDATE PROJECT_ZERO.dbo.TASKS
            SET
                IS_DELETED              = 0,
                TASK_NAME               = @TASK_NAME,
                TASK_DESCRIPTION        = @TASK_DESC,
                TASK_FOR_ROLE_ID        = @TASK_FOR_ROLE_ID,
                EST_HOURS_IT_WILL_TAKE  = @EST_HOURS_IT_TAKES,
                HOURLY_RATE_FOR_TASK    = @HOURLY_PAYMENT_RATE
            WHERE TASK_NAME        = @TASK_NAME
              AND TASK_DESCRIPTION = @TASK_DESC
              AND TASK_FOR_ROLE_ID = @TASK_FOR_ROLE_ID;
    END

    -- =========================================================
    -- UPDATE an existing task by ID
    -- =========================================================
    IF @ACTION = N'UPDATE_TASK'
       AND @TASK_ID IS NOT NULL
    BEGIN
        IF EXISTS (
            SELECT 1 FROM PROJECT_ZERO.dbo.TASKS
            WHERE TASKS_ID = @TASK_ID
        )
            UPDATE PROJECT_ZERO.dbo.TASKS
            SET
                TASK_NAME               = ISNULL(@TASK_NAME,            TASK_NAME),
                TASK_DESCRIPTION        = ISNULL(@TASK_DESC,            TASK_DESCRIPTION),
                TASK_FOR_ROLE_ID        = ISNULL(@TASK_FOR_ROLE_ID,     TASK_FOR_ROLE_ID),
                EST_HOURS_IT_WILL_TAKE  = ISNULL(@EST_HOURS_IT_TAKES,   EST_HOURS_IT_WILL_TAKE),
                HOURLY_RATE_FOR_TASK    = ISNULL(@HOURLY_PAYMENT_RATE,  HOURLY_RATE_FOR_TASK)
            WHERE TASKS_ID = @TASK_ID;
    END

    -- =========================================================
    -- SOFT DELETE a task by ID (sets IS_DELETED = 1)
    -- =========================================================
    IF @ACTION = N'DELETE_TASK'
       AND @TASK_ID IS NOT NULL
    BEGIN
        IF EXISTS (
            SELECT 1 FROM PROJECT_ZERO.dbo.TASKS
            WHERE TASKS_ID = @TASK_ID
        )
            UPDATE PROJECT_ZERO.dbo.TASKS
            SET IS_DELETED = 1
            WHERE TASKS_ID = @TASK_ID;
    END

    SELECT 1 AS STATUS;
END;

CREATE    PROCEDURE CREATE_UPDATE_DELETE_VEHICLE
@ACTION NVARCHAR(50),
@VEHICLE_ID NUMERIC = NULL,
@VEHICLE_NAME NVARCHAR(50) = NULL,
@VEHICLE_LICENCE_PLATE NVARCHAR(50) = NULL
AS
	BEGIN
		SET @ACTION = UPPER(@ACTION)
		
		IF @ACTION = N'CREATE_VEHICLE' AND @VEHICLE_NAME IS NOT NULL AND @VEHICLE_LICENCE_PLATE IS NOT NULL
			BEGIN
				IF NOT EXISTS(SELECT 1 FROM VEHICLE WHERE VEHICLE_NAME = @VEHICLE_NAME AND VEHICLE_LICENCE_PLATE = @VEHICLE_LICENCE_PLATE)
				INSERT INTO VEHICLE
				(
					VEHICLE_NAME,
					VEHICLE_LICENCE_PLATE
				)
				VALUES
				(
					@VEHICLE_NAME,
					@VEHICLE_LICENCE_PLATE
				)
				ELSE
				UPDATE VEHICLE SET IS_DELETED = 0 WHERE VEHICLE_NAME = @VEHICLE_NAME AND VEHICLE_LICENCE_PLATE = @VEHICLE_LICENCE_PLATE
				
			END
		
		IF @ACTION = N'UPDATE_VEHICLE' AND @VEHICLE_ID IS NOT NULL
			BEGIN
				IF EXISTS(SELECT 1 FROM VEHICLE WHERE VEHICLE_ID = @VEHICLE_ID)
				UPDATE VEHICLE
				SET
					VEHICLE_NAME = ISNULL(@VEHICLE_NAME, VEHICLE_NAME),
					VEHICLE_LICENCE_PLATE = ISNULL(@VEHICLE_LICENCE_PLATE, VEHICLE_LICENCE_PLATE)
				WHERE VEHICLE_ID = @VEHICLE_ID
				
			END
		
		IF @ACTION = N'DELETE_VEHICLE' AND @VEHICLE_ID IS NOT NULL
			BEGIN
				IF EXISTS(SELECT 1 FROM VEHICLE WHERE VEHICLE_ID = @VEHICLE_ID)
				UPDATE VEHICLE SET IS_DELETED = 1 WHERE VEHICLE_ID = @VEHICLE_ID
			END
		
		SELECT 1;
	END;

CREATE  
PROCEDURE DELETE_OWNER_SHIP
@SYS_USER_ID NUMERIC,
@INVENTORY_ID NUMERIC,
@FLEET_ID NUMERIC
AS 
BEGIN
	
	IF @SYS_USER_ID IS NOT NULL AND @INVENTORY_ID IS NOT NULL AND @FLEET_ID IS NULL
	BEGIN
		
		DELETE FROM USER_OWNER_SHIP WHERE SYS_USER_ID = @SYS_USER_ID AND INVENTORY_ID = @INVENTORY_ID AND FLEET_ID IS NULL
		
		SELECT 1 AS STATUS
	END
	ELSE IF @SYS_USER_ID IS NOT NULL AND @INVENTORY_ID IS NULL AND @FLEET_ID IS NOT NULL
	BEGIN
		
		DELETE FROM USER_OWNER_SHIP WHERE SYS_USER_ID = @SYS_USER_ID AND INVENTORY_ID IS NULL AND FLEET_ID = @FLEET_ID
		
		SELECT 1 AS STATUS--, @FLEET_ID AS S, @SYS_USER_ID AS D from USER_OWNER_SHIP -- WHERE SYS_USER_ID = @SYS_USER_ID AND INVENTORY_ID IS NULL AND FLEET_ID = @FLEET_ID
	END
	ELSE
	BEGIN
		
		SELECT 0 AS STATUS
		
	END
	
	
END;

CREATE   FUNCTION [dbo].[GET_USER_ID_BY_SESSION]
(@LOGIN_SESSION NVARCHAR(512))
RETURNS NUMERIC
AS
BEGIN
DECLARE @RESULT NUMERIC = (SELECT TOP 1 SYS_USER_ID FROM SYS_USERS WHERE LOGIN_SESSION = @LOGIN_SESSION)
RETURN @RESULT
END;

CREATE   PROCEDURE HANDLE_INVENTORY_REQUEST
    @ACTION                     NVARCHAR(50),
    @INVENTORY_STOCK_REQUEST_ID NUMERIC = NULL,
    @INVENTORY_ID               NUMERIC = NULL,
    @PRODUCTS_ID                NUMERIC = NULL,
    @PRODUCTS_COUNT             NUMERIC = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET @ACTION = UPPER(@ACTION);

    -- =====================================================================
    --  ACTION: SET_REQUEST
    -- =====================================================================
    IF @ACTION = N'SET_REQUEST'
    BEGIN
        -- Validate required parameters
        IF @INVENTORY_ID IS NULL
            THROW 50001, 'INVENTORY_ID cannot be NULL for SET_REQUEST.', 1;
        IF @PRODUCTS_ID IS NULL
            THROW 50001, 'PRODUCTS_ID cannot be NULL for SET_REQUEST.', 1;
        IF @PRODUCTS_COUNT IS NULL
            THROW 50001, 'PRODUCTS_COUNT cannot be NULL for SET_REQUEST.', 1;

        INSERT INTO INVENTORY_STOCK_REQUEST
        (
            INVENTORY_ID,
            PRODUCTS_ID,
            IS_DELETED,
            DRIVER_ID_ASSIGNED,
            PRODUCTS_COUNT
        )
        VALUES
        (
            @INVENTORY_ID,
            @PRODUCTS_ID,
            0,                  -- IS_DELETED
            NULL,                  -- IS_ACCEPTED_BY_FLEET (default false)
            @PRODUCTS_COUNT     -- PRODUCTS_COUNT (fixed order)
        );
    END

    -- =====================================================================
    --  ACTION: ACCEPT_REQUEST
    -- =====================================================================
    IF @ACTION = N'ACCEPT_REQUEST'
    BEGIN
        -- Validate required parameters
        IF @INVENTORY_STOCK_REQUEST_ID IS NULL
            THROW 50002, 'INVENTORY_STOCK_REQUEST_ID cannot be NULL for ACCEPT_REQUEST.', 1;
        IF @INVENTORY_ID IS NULL
            THROW 50002, 'INVENTORY_ID cannot be NULL for ACCEPT_REQUEST.', 1;
        IF @PRODUCTS_ID IS NULL
            THROW 50002, 'PRODUCTS_ID cannot be NULL for ACCEPT_REQUEST.', 1;

        -- Check that the request exists and is not deleted
        IF NOT EXISTS (
            SELECT 1
            FROM INVENTORY_STOCK_REQUEST
            WHERE INVENTORY_STOCK_REQUEST_ID = @INVENTORY_STOCK_REQUEST_ID
              AND IS_DELETED = 0
        )
            THROW 50003, 'Request not found or has been deleted.', 1;

        -- Ensure source and destination inventories are different
        IF EXISTS (
            SELECT 1
            FROM INVENTORY_STOCK_REQUEST
            WHERE INVENTORY_STOCK_REQUEST_ID = @INVENTORY_STOCK_REQUEST_ID
              AND INVENTORY_ID = @INVENTORY_ID
        )
            THROW 50004, 'Source and destination inventory cannot be the same.', 1;

        -- Perform the update
        UPDATE INVENTORY_STOCK_REQUEST
        SET
            FROM_INVENTORY_ID         = @INVENTORY_ID,
            PRODUCTS_ID             = @PRODUCTS_ID,
            ACCEPT_BY_INVENTORY_ID  = @INVENTORY_ID
        WHERE INVENTORY_STOCK_REQUEST_ID = @INVENTORY_STOCK_REQUEST_ID;
    END
    SELECT 1 AS STATUS
END;

CREATE   PROCEDURE [dbo].[IS_ALLOWED]
@LOGIN_SESSION NVARCHAR(512),
@SYS_OBJECT_CODE NUMERIC
AS
BEGIN

	IF EXISTS (SELECT 1 FROM SYS_CALL_ACCESS WHERE SYS_OBJECT_CODE = @SYS_OBJECT_CODE AND ROLE_CODE IN
	(SELECT ROLE_CODE FROM USERS_ROLES WHERE ISNULL(IS_ACTIVE ,1) = 1 AND SYS_USER_ID = 
	(SELECT SYS_USER_ID FROM SYS_USERS WHERE LOGIN_SESSION = @LOGIN_SESSION)))
	BEGIN
		SELECT 1 AS RESULT
	END
	ELSE
	BEGIN
		SELECT 0 AS RESULT
	END
END;

CREATE   PROCEDURE [dbo].[IS_ALLOWED_READ]
@LOGIN_SESSION NVARCHAR(512),
@SYS_OBJECT_CODE NUMERIC
AS
BEGIN

	IF EXISTS (SELECT 1 FROM SYS_CALL_ACCESS WHERE CAN_READ = 1 AND SYS_OBJECT_CODE = @SYS_OBJECT_CODE AND ROLE_CODE IN
	(SELECT ROLE_CODE FROM USERS_ROLES WHERE ISNULL(IS_ACTIVE ,1) = 1 AND SYS_USER_ID = 
	(SELECT SYS_USER_ID FROM SYS_USERS WHERE LOGIN_SESSION = @LOGIN_SESSION)))
	BEGIN
		SELECT 1 AS RESULT
	END
	ELSE
	BEGIN
		SELECT 0 AS RESULT
	END
END;

CREATE   PROCEDURE [dbo].[IS_AUTHENTICATED]	
@TOKEN NVARCHAR(MAX)
AS
BEGIN
	SELECT TOP 1
	CASE
	WHEN EXISTS(SELECT 1 FROM SYS_USERS WHERE LOGIN_SESSION = @TOKEN)
	THEN
	1
	ELSE
	0 
	END AS RESULT
	FROM SYS_USERS
END;

CREATE   FUNCTION [dbo].[LOGIN_LOG_SELECT]
(
@TOKEN NVARCHAR(512)
)
RETURNS TABLE
AS
RETURN
(
	SELECT
	USER_LOGIN_LOG_ID, USERNAME, LOGIN_DATE
	FROM USER_LOGIN_LOG ULL
	INNER JOIN
	SYS_USERS SU
	ON ULL.SYS_USER_ID = SU.SYS_USER_ID
	WHERE SU.LOGIN_SESSION = @TOKEN
);

CREATE   PROCEDURE [dbo].[LOGIN_VALID]
@USERNAME NVARCHAR(50),
@PASSWORD NVARCHAR(50)
AS
BEGIN
DECLARE @USER_ID NUMERIC = (SELECT SYS_USER_ID FROM SYS_USERS WHERE LOWER(USERNAME) = LOWER(@USERNAME) AND USER_PASSWORD = HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @PASSWORD, N'4THEYS123#AYIMJO31SEPHSEED')));
	IF @USER_ID IS NOT NULL
	BEGIN
		DECLARE @TOKENVARBINARY VARBINARY(512)
		SET @TOKENVARBINARY = HASHBYTES('SHA2_512', CONCAT(N'I%@MBAR#4BI$GI$RL', @USERNAME, N'4THEYS123#AYIMJO31SEPHSEED', CAST(GETUTCDATE() AS NVARCHAR)))
		
		DECLARE @TOKEN NVARCHAR(512) = CONVERT(NVARCHAR(512), @TOKENVARBINARY, 2);
		
		UPDATE SYS_USERS
		SET
		LOGIN_SESSION = @TOKEN
		WHERE SYS_USER_ID = @USER_ID

		INSERT INTO USER_LOGIN_LOG (SYS_USER_ID, LOGIN_DATE) VALUES (@USER_ID, CONVERT(NVARCHAR(19), GETDATE(), 120))
		
		SELECT 1 AS RESULT, @TOKEN AS TOKEN
	END
	ELSE
	SELECT 0 AS RESULT, N'' AS TOKEN
END;

CREATE   PROCEDURE MANAGE_DRIVERS_AND_TEAMS
    @ACTION NVARCHAR(50),
    @DRIVER_NAME NVARCHAR(50) = NULL,
    @DRIVER_LAST_NAME NVARCHAR(50) = NULL,
    @DRIVERS_NATIONAL_CODE NVARCHAR(50) = NULL,
    @NEW_DRIVER_NAME NVARCHAR(50) = NULL,
    @NEW_DRIVER_LAST_NAME NVARCHAR(50) = NULL,
    @NEW_DRIVERS_NATIONAL_CODE NVARCHAR(50) = NULL,
    @DRIVERS_PHONE_NUMBER NVARCHAR(50) = NULL,
    @NEW_DRIVERS_PHONE_NUMBER NVARCHAR(50) = NULL,
    @FLEET_TEAM_NAME NVARCHAR(50) = NULL,
    @NEW_FLEET_TEAM_NAME NVARCHAR(50) = NULL,
    @DESCRIPTION NVARCHAR(100) = NULL,
    @NEW_DESCRIPTION NVARCHAR(100) = NULL
AS
BEGIN
	DECLARE @FLEET_ID NUMERIC = (SELECT TOP 1 FLEET_TEAM_ID FROM FLEET_TEAMS WHERE LOWER(FLEET_TEAM_NAME) LIKE LOWER(@FLEET_TEAM_NAME))
    -- ========== DRIVERS ==========
    IF LOWER(@ACTION) = LOWER(N'ADD_DRIVER')
       AND @DRIVERS_NATIONAL_CODE IS NOT NULL
       AND @DRIVER_NAME IS NOT NULL
       AND @DRIVER_LAST_NAME IS NOT NULL
       AND @DRIVERS_PHONE_NUMBER IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM DRIVERS WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE)
            INSERT INTO DRIVERS (DRIVER_NAME, DRIVER_LAST_NAME, DRIVERS_NATIONAL_CODE, DRIVERS_PHONE_NUMBER, IS_DELETED,FLEET_TEAM_ID)
            VALUES (@DRIVER_NAME, @DRIVER_LAST_NAME, @DRIVERS_NATIONAL_CODE, @DRIVERS_PHONE_NUMBER, 0, @FLEET_ID);
        ELSE
            UPDATE DRIVERS SET IS_DELETED = 0 WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE;
    END

    IF LOWER(@ACTION) = LOWER(N'MODIFY_DRIVER')
       AND @DRIVERS_NATIONAL_CODE IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM DRIVERS WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE)
            UPDATE DRIVERS
            SET DRIVER_NAME = ISNULL(@NEW_DRIVER_NAME, DRIVER_NAME),
                DRIVER_LAST_NAME = ISNULL(@NEW_DRIVER_LAST_NAME, DRIVER_LAST_NAME),
                DRIVERS_NATIONAL_CODE = ISNULL(@NEW_DRIVERS_NATIONAL_CODE, DRIVERS_NATIONAL_CODE),
                DRIVERS_PHONE_NUMBER = ISNULL(@NEW_DRIVERS_PHONE_NUMBER, DRIVERS_PHONE_NUMBER),
                FLEET_TEAM_ID = ISNULL(@FLEET_ID, FLEET_TEAM_ID)
            WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE;
    END

    IF LOWER(@ACTION) = LOWER(N'DELETE_DRIVER')
       AND @DRIVERS_NATIONAL_CODE IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM DRIVERS WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE)
            UPDATE DRIVERS SET IS_DELETED = 1 WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE;
    END

    -- ========== FLEET TEAMS ==========
    IF LOWER(@ACTION) = LOWER(N'ADD_FLEET_TEAM')
       AND @FLEET_TEAM_NAME IS NOT NULL
       AND @DESCRIPTION IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM FLEET_TEAMS WHERE FLEET_TEAM_NAME = @FLEET_TEAM_NAME)
            INSERT INTO FLEET_TEAMS (FLEET_TEAM_NAME, DESCRIPTION, IS_DELETED)
            VALUES (@FLEET_TEAM_NAME, @DESCRIPTION, 0);
        ELSE
            UPDATE FLEET_TEAMS SET IS_DELETED = 0 WHERE FLEET_TEAM_NAME = @FLEET_TEAM_NAME;
    END

    IF LOWER(@ACTION) = LOWER(N'MODIFY_FLEET_TEAM')
       AND @FLEET_TEAM_NAME IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM FLEET_TEAMS WHERE FLEET_TEAM_NAME = @FLEET_TEAM_NAME)
            UPDATE FLEET_TEAMS
            SET FLEET_TEAM_NAME = ISNULL(@NEW_FLEET_TEAM_NAME, FLEET_TEAM_NAME),
                DESCRIPTION = ISNULL(@NEW_DESCRIPTION, DESCRIPTION)
            WHERE FLEET_TEAM_NAME = @FLEET_TEAM_NAME;
    END

    IF LOWER(@ACTION) = LOWER(N'DELETE_FLEET_TEAM')
       AND @FLEET_TEAM_NAME IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM FLEET_TEAMS WHERE FLEET_TEAM_NAME = @FLEET_TEAM_NAME)
            UPDATE FLEET_TEAMS SET IS_DELETED = 1 WHERE FLEET_TEAM_NAME = @FLEET_TEAM_NAME;
    END

    SELECT 1;
END;

CREATE    PROCEDURE MANAGE_INVENTORY_INFSTRUCTURE
@ACTION NVARCHAR(50),
@INVENTORY_LOCATION_TITLE NVARCHAR(50) = NULL,
@NEW_INVENTORY_LOCATION_TITLE NVARCHAR(50) = NULL,
@PRODUCTS_NAME NVARCHAR(50) = NULL,
@NEW_PRODUCTS_NAME NVARCHAR(50) = NULL,
@PRODUCTS_CATEGORY_ID NUMERIC = NULL,
@PRODUCTS_CATEGORY_NAME NVARCHAR(50) = NULL,
@NEW_PRODUCTS_CATEGORY_NAME NVARCHAR(50) = NULL
AS
	BEGIN
		
		IF LOWER(@ACTION) = LOWER(N'ADD_INVENTORY_TYPE') AND @INVENTORY_LOCATION_TITLE IS NOT NULL
		BEGIN
			IF NOT EXISTS(SELECT 1 FROM LT_INVENTORY_LOCATION_TYPE WHERE INVENTORY_LOCATION_TYPE_TITLE LIKE @INVENTORY_LOCATION_TITLE)
			INSERT INTO LT_INVENTORY_LOCATION_TYPE  (INVENTORY_LOCATION_TYPE_TITLE) VALUES (@INVENTORY_LOCATION_TITLE)
			ELSE
			UPDATE LT_INVENTORY_LOCATION_TYPE SET IS_DELETED = 0 WHERE INVENTORY_LOCATION_TYPE_TITLE LIKE @INVENTORY_LOCATION_TITLE
		END
		
		IF LOWER(@ACTION) = LOWER(N'MODIFY_INVENTORY_TYPE') AND @INVENTORY_LOCATION_TITLE IS NOT NULL
		BEGIN
			IF EXISTS(SELECT 1 FROM LT_INVENTORY_LOCATION_TYPE WHERE INVENTORY_LOCATION_TYPE_TITLE LIKE @INVENTORY_LOCATION_TITLE)
			UPDATE LT_INVENTORY_LOCATION_TYPE SET INVENTORY_LOCATION_TYPE_TITLE = @NEW_INVENTORY_LOCATION_TITLE WHERE INVENTORY_LOCATION_TYPE_TITLE LIKE @INVENTORY_LOCATION_TITLE
		END
		
		IF LOWER(@ACTION) = LOWER(N'DELETE_INVENTORY_TYPE') AND @INVENTORY_LOCATION_TITLE IS NOT NULL
		BEGIN
			IF EXISTS(SELECT 1 FROM LT_INVENTORY_LOCATION_TYPE WHERE INVENTORY_LOCATION_TYPE_TITLE LIKE @INVENTORY_LOCATION_TITLE)
			UPDATE LT_INVENTORY_LOCATION_TYPE SET IS_DELETED = 1 WHERE INVENTORY_LOCATION_TYPE_TITLE LIKE @INVENTORY_LOCATION_TITLE
		END
		
		IF LOWER(@ACTION) = LOWER(N'ADD_PRODUCTS_CATEGORY') AND @PRODUCTS_CATEGORY_NAME IS NOT NULL 
		BEGIN
			IF NOT EXISTS (SELECT 1 FROM PRODUCTS_CATEGORY WHERE PRODUCTS_CATEGORY_NAME = @PRODUCTS_CATEGORY_NAME)
			INSERT INTO PRODUCTS_CATEGORY (PRODUCTS_CATEGORY_NAME) VALUES (@PRODUCTS_CATEGORY_NAME)
			ELSE
			UPDATE PRODUCTS_CATEGORY SET IS_DELETED = 0 WHERE PRODUCTS_CATEGORY_NAME = @PRODUCTS_CATEGORY_NAME
		END
		
		IF LOWER(@ACTION) = LOWER(N'MODIFY_PRODUCTS_CATEGORY') AND @PRODUCTS_CATEGORY_NAME IS NOT NULL 
		BEGIN
			IF EXISTS (SELECT 1 FROM PRODUCTS_CATEGORY WHERE PRODUCTS_CATEGORY_NAME = @PRODUCTS_CATEGORY_NAME)
			UPDATE PRODUCTS_CATEGORY SET PRODUCTS_CATEGORY_NAME = @NEW_PRODUCTS_CATEGORY_NAME WHERE PRODUCTS_CATEGORY_NAME = @PRODUCTS_CATEGORY_NAME
		END
		
		IF LOWER(@ACTION) = LOWER(N'DELETE_PRODUCTS_CATEGORY') AND @PRODUCTS_CATEGORY_NAME IS NOT NULL 
		BEGIN
			IF EXISTS (SELECT 1 FROM PRODUCTS_CATEGORY WHERE PRODUCTS_CATEGORY_NAME = @PRODUCTS_CATEGORY_NAME)
			UPDATE PRODUCTS_CATEGORY SET IS_DELETED = 1 WHERE PRODUCTS_CATEGORY_NAME = @PRODUCTS_CATEGORY_NAME
		END
		
		IF LOWER(@ACTION) = LOWER(N'ADD_PRODUCTS') AND @PRODUCTS_NAME IS NOT NULL AND @PRODUCTS_CATEGORY_ID IS NOT NULL
		BEGIN
			IF NOT EXISTS(SELECT 1 FROM PRODUCTS WHERE PRODUCTS_NAME = @PRODUCTS_NAME)
			INSERT INTO PRODUCTS (PRODUCTS_NAME, PRODUCTS_CATEGORY_ID, IS_DELETED) VALUES (@PRODUCTS_NAME, @PRODUCTS_CATEGORY_ID, 0)
			ELSE
			UPDATE PRODUCTS SET IS_DELETED = 0 WHERE PRODUCTS_NAME = @PRODUCTS_NAME
		END
		
		IF LOWER(@ACTION) = LOWER(N'MODIFY_PRODUCTS')
		BEGIN
			IF EXISTS(SELECT 1 FROM PRODUCTS WHERE PRODUCTS_NAME = @PRODUCTS_NAME)
			UPDATE PRODUCTS SET PRODUCTS_NAME = ISNULL(@NEW_PRODUCTS_NAME, PRODUCTS_NAME), PRODUCTS_CATEGORY_ID = ISNULL(@PRODUCTS_CATEGORY_ID, PRODUCTS_CATEGORY_ID) WHERE PRODUCTS_NAME = @PRODUCTS_NAME
		END
		
		IF LOWER(@ACTION) = LOWER(N'DELETE_PRODUCTS') AND @PRODUCTS_NAME IS NOT NULL
		BEGIN
			IF EXISTS(SELECT 1 FROM PRODUCTS WHERE PRODUCTS_NAME = @PRODUCTS_NAME)
			UPDATE PRODUCTS SET IS_DELETED = 1 WHERE PRODUCTS_NAME = @PRODUCTS_NAME
		END
		
		SELECT 1;
	END;

CREATE   PROCEDURE MANAGE_INVENTORY_STOCK_REQUEST
    @ACTION NVARCHAR(50),
    @INVENTORY_STOCK_REQUEST_ID NUMERIC(18,0) = NULL,
    @DRIVER_ID NUMERIC(18,0) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    -- MODE 1: Return request details (including lat/long)
    IF LOWER(@ACTION) = LOWER(N'GET_REQUEST_DETAILS')
       AND @INVENTORY_STOCK_REQUEST_ID IS NOT NULL
    BEGIN
        SELECT
            isr.INVENTORY_STOCK_REQUEST_ID,
            il.INVENTORY_LOCATION_NAME        AS REQUESTING_INVENTORY,
            il.INVENTORY_LOCATION_LAT         AS REQUESTING_LAT,
            il.INVENTORY_LOCATION_LONG        AS REQUESTING_LONG,
            il2.INVENTORY_LOCATION_NAME       AS SUPPLYING_INVENTORY,
            il2.INVENTORY_LOCATION_LAT        AS SUPPLYING_LAT,
            il2.INVENTORY_LOCATION_LONG       AS SUPPLYING_LONG,
            p.PRODUCTS_ID,
            p.PRODUCTS_NAME,
            isr.PRODUCTS_COUNT,
            isr.IS_GET,
            CASE WHEN isr.DRIVER_ID_ASSIGNED IS NOT NULL 
                 THEN 1 ELSE 0 
            END AS IS_ACCEPTED_BY_FLEET
        FROM INVENTORY_STOCK_REQUEST isr
        LEFT JOIN PRODUCTS p ON p.PRODUCTS_ID = isr.PRODUCTS_ID
        LEFT JOIN INVENTORY_LOCATION il ON il.INVENTORY_LOCATION_ID = isr.INVENTORY_ID
        LEFT JOIN INVENTORY_LOCATION il2 ON il2.INVENTORY_LOCATION_ID = isr.FROM_INVENTORY_ID
        WHERE isr.INVENTORY_STOCK_REQUEST_ID = @INVENTORY_STOCK_REQUEST_ID
          AND isr.IS_DELETED = 0;
    END

    -- MODE 2: Accept the trip – assign a driver
    IF LOWER(@ACTION) = LOWER(N'ACCEPT_REQUEST')
       AND @INVENTORY_STOCK_REQUEST_ID IS NOT NULL
       AND @DRIVER_ID IS NOT NULL
    BEGIN
        UPDATE INVENTORY_STOCK_REQUEST
        SET DRIVER_ID_ASSIGNED = @DRIVER_ID
        WHERE INVENTORY_STOCK_REQUEST_ID = @INVENTORY_STOCK_REQUEST_ID
          AND IS_DELETED = 0
          AND DRIVER_ID_ASSIGNED IS NULL;

        SELECT 1;
    END
END;

CREATE    PROCEDURE MANAGE_PRODUCTS_MOVEMENT_TRIPS
@ACTION NVARCHAR(50) = NULL,
@PRODUCTS_MOVEMENTS_ID NUMERIC = NULL,
@DRIVERS_ID NUMERIC = NULL,
@VEHICLE_ID NUMERIC = NULL,
@COMES_FROM_LOCATION_ID NUMERIC = NULL,
@GOES_TO_LOCATION_ID NUMERIC = NULL,
@EST_ARIVAL NVARCHAR(19) = NULL,
@DID_ARIVE BIT = NULL,
@PRODUCTS_MOVEMENTS_LIST_ID NUMERIC = NULL,
@PRODUCTS_ID NUMERIC = NULL,
@PRODUCTS_COUNT NUMERIC = NULL
AS
	BEGIN
	
	SET @ACTION = UPPER(@ACTION)

		IF @ACTION = N'DELETE_TRIP'
		AND @PRODUCTS_MOVEMENTS_ID IS NOT NULL
		AND (SELECT TOP(1) START_DATE_HOUR FROM PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NULL
		BEGIN
			UPDATE PRODUCTS_MOVEMENTS
				SET 
					IS_DELETED = 1,
					IS_ACTIVE = 0
				WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID
			
			DELETE FROM MOVEMENTS_PRODUCTS_LIST WHERE MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID
		END
		
		IF @ACTION = N'ADD_PRODUCT_TO_TRIP'
		AND @PRODUCTS_MOVEMENTS_ID IS NOT NULL 
        AND @PRODUCTS_ID IS NOT NULL 
        AND @PRODUCTS_COUNT IS NOT NULL
        AND (SELECT TOP(1) START_DATE_HOUR FROM PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NULL
			BEGIN
				INSERT INTO MOVEMENTS_PRODUCTS_LIST 
				(
					MOVEMENTS_ID,
					PRODUCTS_ID,
					PRODUCTS_COUNT
				)
				VALUES
				(
					@PRODUCTS_MOVEMENTS_ID,
					@PRODUCTS_ID,
					@PRODUCTS_COUNT
				)
			END
			
		IF @ACTION = N'DELETE_PRODUCT_FROM_TRIP' AND @PRODUCTS_MOVEMENTS_LIST_ID IS NOT NULL
		AND (SELECT TOP(1) START_DATE_HOUR FROM PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NULL
			BEGIN
				DELETE FROM MOVEMENTS_PRODUCTS_LIST WHERE MOVEMENTS_PRODUCTS_ID = @PRODUCTS_MOVEMENTS_LIST_ID
			END
			
		IF @ACTION = N'MODIFY_PRODUCT_FROM_TRIP' AND @PRODUCTS_MOVEMENTS_LIST_ID IS NOT NULL
		AND (SELECT TOP(1) START_DATE_HOUR FROM PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NULL
			BEGIN
				UPDATE MOVEMENTS_PRODUCTS_LIST
				SET
					PRODUCTS_ID = ISNULL(@PRODUCTS_ID, PRODUCTS_ID),
					PRODUCTS_COUNT = ISNULL(@PRODUCTS_COUNT, PRODUCTS_COUNT) 
				WHERE MOVEMENTS_PRODUCTS_ID = @PRODUCTS_MOVEMENTS_LIST_ID
			END	
		
	
		IF @ACTION = N'ADD_PRODUCTS_TRIP'
        AND @DRIVERS_ID IS NOT NULL
        AND @VEHICLE_ID IS NOT NULL
        AND @COMES_FROM_LOCATION_ID IS NOT NULL
        AND @GOES_TO_LOCATION_ID IS NOT NULL
        AND @COMES_FROM_LOCATION_ID <> @GOES_TO_LOCATION_ID
		BEGIN
			
			INSERT INTO PRODUCTS_MOVEMENTS (
			    DRIVERS_ID,
			    VEHICLE_ID,
			    COMES_FROM_LOCATION_ID,
			    GOES_TO_LOCATION_ID
			)
			VALUES (
			    @DRIVERS_ID,
			    @VEHICLE_ID,
			    @COMES_FROM_LOCATION_ID,
			    @GOES_TO_LOCATION_ID
			)
		END
		
		IF @ACTION = N'MODIFY_TRIP' --THIS IS FOR NOT STARTED TRIPS ONLY
		AND @PRODUCTS_MOVEMENTS_ID IS NOT NULL
		AND (SELECT START_DATE_HOUR FROM PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NULL
			BEGIN
				
				UPDATE PRODUCTS_MOVEMENTS
					SET 
					    DRIVERS_ID = ISNULL(@DRIVERS_ID, DRIVERS_ID),
					    VEHICLE_ID = ISNULL(@VEHICLE_ID, VEHICLE_ID),
					    COMES_FROM_LOCATION_ID = ISNULL(@COMES_FROM_LOCATION_ID, COMES_FROM_LOCATION_ID),
					    GOES_TO_LOCATION_ID = ISNULL(@GOES_TO_LOCATION_ID, GOES_TO_LOCATION_ID)
					WHERE 
					    PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID
				
			END
			
		IF @ACTION = N'START_TRIP' AND @PRODUCTS_MOVEMENTS_ID IS NOT NULL
		AND (SELECT START_DATE_HOUR FROM PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NULL
			BEGIN
				
				UPDATE PRODUCTS_MOVEMENTS
					SET 
					    START_DATE_HOUR = CONVERT(NVARCHAR(19), GETDATE(), 20),
					    EST_ARIVAL = ISNULL(@EST_ARIVAL, EST_ARIVAL)
					WHERE 
					    PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID
			END
			
			
		IF @ACTION = N'END_TRIP' AND @PRODUCTS_MOVEMENTS_ID IS NOT NULL
		AND (SELECT END_DATE_HOUR FROM PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NULL
		AND (SELECT START_DATE_HOUR FROM PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NOT NULL
			BEGIN
				UPDATE PRODUCTS_MOVEMENTS
					SET 
					    END_DATE_HOUR = CONVERT(NVARCHAR(19), GETDATE(), 20),
					    DID_ARIVE = ISNULL(@DID_ARIVE, DID_ARIVE),
					    IS_ACTIVE = 0
					WHERE 
					    PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID
			END
			
			
		SELECT 1
		
	END;

CREATE   FUNCTION [dbo].[ROLES_LOG_SELECT]
(
@TOKEN NVARCHAR(512)
)
RETURNS TABLE
AS
RETURN
(
	SELECT
	UR.USERS_ROLES_ID,
	LR.ROLES_TITLE,
	UR.ASSIGNMENT_DATE
	FROM USERS_ROLES UR
	INNER JOIN
	SYS_USERS SU
	ON UR.SYS_USER_ID = SU.SYS_USER_ID
	INNER JOIN LT_ROLES LR
	ON UR.ROLE_CODE = LR.ROLE_CODE
	WHERE (SU.LOGIN_SESSION = @TOKEN) AND UR.IS_ACTIVE = 1
);

CREATE   PROCEDURE [dbo].[ROLES_MANAGEMENT] 
@USERNAME NVARCHAR(50),
@ROLES_TITLE NVARCHAR(50),
@REVOKE BIT = 0
AS
BEGIN

DECLARE @SYS_USER_ID NUMERIC = (SELECT TOP 1 SYS_USER_ID FROM SYS_USERS WHERE LOWER(USERNAME) LIKE LOWER(@USERNAME))
DECLARE @ROLE_CODE NUMERIC = (SELECT TOP 1 ROLE_CODE FROM LT_ROLES WHERE LOWER(ROLES_TITLE) LIKE LOWER(@ROLES_TITLE))
DECLARE @EXISTS BIT = 0;

IF EXISTS( SELECT 1 FROM USERS_ROLES WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE)
BEGIN
SET @EXISTS = 1
END

IF @SYS_USER_ID IS NOT NULL AND @ROLE_CODE IS NOT NULL
	BEGIN
	IF NOT(@REVOKE = 1)
		BEGIN
		IF @EXISTS = 1
			BEGIN
			
			UPDATE USERS_ROLES SET IS_ACTIVE = 1 WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE
			END
		ELSE
			BEGIN
			
			INSERT INTO USERS_ROLES (SYS_USER_ID, ROLE_CODE, ASSIGNMENT_DATE, IS_ACTIVE) VALUES (@SYS_USER_ID, @ROLE_CODE, CONVERT(NVARCHAR(19), GETDATE(), 120), 1)
			END
		END
	ELSE
		BEGIN
		
		IF @EXISTS = 1
		UPDATE USERS_ROLES SET IS_ACTIVE = 0 WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE
		END
	END

	SELECT 1 AS STATUS
	
END;

CREATE     PROCEDURE [dbo].[ROLES_MANAGEMENT_ID_BASED] 
@REVOKE BIT = 0,
@SYS_USER_ID NUMERIC,
@ROLE_CODE NUMERIC
AS
BEGIN

DECLARE @EXISTS BIT = 0;
IF EXISTS( SELECT 1 FROM USERS_ROLES WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE)
BEGIN
SET @EXISTS = 1
END

IF @SYS_USER_ID IS NOT NULL AND @ROLE_CODE IS NOT NULL
	BEGIN
	IF NOT(@REVOKE = 1)
		BEGIN
		IF @EXISTS = 1
			BEGIN
			UPDATE USERS_ROLES SET IS_ACTIVE = 1 WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE
			
			END
		ELSE
			BEGIN
			INSERT INTO USERS_ROLES (SYS_USER_ID, ROLE_CODE, ASSIGNMENT_DATE, IS_ACTIVE) VALUES (@SYS_USER_ID, @ROLE_CODE, CONVERT(NVARCHAR(19), GETDATE(), 120), 1)
			
			END
		END
	ELSE
		BEGIN
		
		IF @EXISTS = 1
		UPDATE USERS_ROLES SET IS_ACTIVE = 0 WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE
		END
	END
	SELECT 1 AS STATUS
END;

CREATE   PROCEDURE SET_OWNER_SHIP
@SYS_USER_ID NUMERIC,
@INVENTORY_ID NUMERIC,
@FLEET_ID NUMERIC
AS 
BEGIN
	
	IF @SYS_USER_ID IS NOT NULL AND @INVENTORY_ID IS NOT NULL AND @FLEET_ID IS NULL
	BEGIN
		
		INSERT INTO USER_OWNER_SHIP (SYS_USER_ID ,INVENTORY_ID, FLEET_ID) VALUES (@SYS_USER_ID, @INVENTORY_ID, NULL)
		
		SELECT 1 AS STATUS
	END
	ELSE IF @SYS_USER_ID IS NOT NULL AND @INVENTORY_ID IS NULL AND @FLEET_ID IS NOT NULL
	BEGIN
		
		INSERT INTO USER_OWNER_SHIP (SYS_USER_ID ,FLEET_ID, INVENTORY_ID) VALUES (@SYS_USER_ID, @FLEET_ID, NULL)
		
		SELECT 1 AS STATUS
	END
	ELSE
	BEGIN
		
		SELECT 0 AS STATUS
		
	END
	
	
END;

CREATE   PROCEDURE [dbo].[SIGNUP_NEWUSER]
@USERNAME NVARCHAR(50),
@PASSWORD NVARCHAR(100)
AS
BEGIN
  IF NOT EXISTS(SELECT 1 FROM SYS_USERS WHERE LOWER(USERNAME) LIKE LOWER(@USERNAME))
  BEGIN
  INSERT INTO [SYS_USERS]
  (
  [USERNAME],
  USER_PASSWORD
  )
  VALUES
  (
  LOWER(@USERNAME),
  HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @PASSWORD, N'4THEYS123#AYIMJO31SEPHSEED'))
  )
  SELECT 1 AS RESULT
  END
  ELSE
  BEGIN
  SELECT 0 AS RESULT
  END
END;

CREATE   PROCEDURE [dbo].[TASKS_REPORT]
@BY_USER_SESSION NVARCHAR(512) = NULL,
@TASK_ID_ACCPETED NUMERIC = NULL,
@END_TASK BIT = NULL
AS
BEGIN
BEGIN TRANSACTION
--DECLARE @TEMP NVARCHAR(MAX)
IF @TASK_ID_ACCPETED IS NOT NULL AND @BY_USER_SESSION IS NOT NULL AND EXISTS(SELECT 1 FROM TASKS WHERE TASKS_ID = @TASK_ID_ACCPETED) AND NOT @END_TASK = 1
BEGIN
BEGIN TRY
UPDATE TASKS
SET
ACCEPTED_BY_SYS_USER_ID = DBO.GET_USER_ID_BY_SESSION(@BY_USER_SESSION),
START_DATE_TIME = CONVERT(NVARCHAR(19), GETDATE(), 120)
WHERE TASKS_ID = @TASK_ID_ACCPETED
--SET @TEMP = (N'USER ACCEPTED A TASK WITH TASK ID : ' + @TASK_ID_ACCPETED)
--EXEC ACTIVITY_LOG_MANAGER 0, @BY_USER_SESSION, @TEMP
END TRY
BEGIN CATCH
ROLLBACK;
END CATCH
END

IF @END_TASK = 1
BEGIN
BEGIN TRY
UPDATE TASKS
SET
END_DATE_TIME = CONVERT(NVARCHAR(19), GETDATE(), 120),
ACTUAL_TIME_TASK_TOOK = (SELECT TOP 1 DATEDIFF(
    SECOND,
    CONVERT(DATETIME, START_DATE_TIME),
    CONVERT(DATETIME, CONVERT(NVARCHAR(19), GETDATE(), 120))
) AS HoursDifference FROM TASKS WHERE TASKS_ID = @TASK_ID_ACCPETED) / 3600.0
WHERE TASKS_ID = @TASK_ID_ACCPETED

INSERT INTO WORK_HOUR_REPORT_LOG
(SYS_USER_ID, COMPLETED_TASK_ID)
VALUES
((SELECT TOP 1 SYS_USER_ID FROM SYS_USERS WHERE LOGIN_SESSION = @BY_USER_SESSION) ,@TASK_ID_ACCPETED)
--SET @TEMP = (N'USER ENDED A TASK WITH TASK ID : ' + @TASK_ID_ACCPETED)
--EXEC ACTIVITY_LOG_MANAGER 0, @BY_USER_SESSION, @TEMP
END TRY
BEGIN CATCH
ROLLBACK;
END CATCH
END

SELECT 
TASKS_ID,
TASK_NAME,
TASK_DESCRIPTION,
TASK_FOR_ROLE_ID,
CASE
WHEN START_DATE_TIME IS NULL
THEN N'No one has accepted this task yet'
ELSE
START_DATE_TIME
END AS START_DATE_TIME
,
CASE
WHEN START_DATE_TIME IS NULL
THEN N'No one has finished this task yet'
ELSE
END_DATE_TIME
END AS END_DATE_TIME
,EST_HOURS_IT_WILL_TAKE
,HOURLY_RATE_FOR_TASK
,SU.USERNAME AS TASK_CREATED_BY
FROM TASKS T
INNER JOIN SYS_USERS SU
ON SU.SYS_USER_ID = T.TASK_CREATED_BY_SYS_USER_ID WHERE ISNULL(T.IS_DELETED, 0) = 0
COMMIT

END;

CREATE   PROCEDURE UPDATING_LIST_OF_SYS_OBJECTS
@SYS_OBJECT_NAME NVARCHAR(100),
@SYS_OBJECT_CODE NUMERIC

AS
	BEGIN
		
		IF NOT EXISTS(SELECT 1 FROM SYS_OBJECTS WHERE SYS_OBJECT_NAME = @SYS_OBJECT_NAME AND SYS_OBJECT_CODE = @SYS_OBJECT_CODE)
			BEGIN
				INSERT INTO SYS_OBJECTS (SYS_OBJECT_NAME, SYS_OBJECT_CODE) VALUES (@SYS_OBJECT_NAME, @SYS_OBJECT_CODE)
				SELECT N'CREATED NEW SYS OBJECT' AS STATUS
			END
		ELSE
			BEGIN
				SELECT N'SYS OBJECT FOUND' AS STATUS
			END
	END;

CREATE   PROCEDURE USP_CREATE_MOVEMENT_FROM_STOCK_REQUEST
    @RequestIDs NVARCHAR(MAX),      -- e.g. '1|2|3'
    @VehicleID  NUMERIC(18,0)       -- vehicle to assign to the movement
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        -- 1. Split the pipe-separated IDs into a table
        DECLARE @ParsedIDs TABLE (ID NUMERIC(18,0));
        INSERT INTO @ParsedIDs (ID)
        SELECT CAST(value AS NUMERIC(18,0))
        FROM STRING_SPLIT(@RequestIDs, '|')
        WHERE RTRIM(value) <> '';

        IF NOT EXISTS (SELECT 1 FROM @ParsedIDs)
        BEGIN
            ROLLBACK TRANSACTION;
            SELECT (SELECT 0 AS Status, 0 AS MovementID FOR JSON PATH) AS Result;
            RETURN;
        END

        -- 2. Check that every ID exists and is NOT already deleted
        IF EXISTS (
            SELECT 1
            FROM @ParsedIDs p
            LEFT JOIN INVENTORY_STOCK_REQUEST r
                ON p.ID = r.INVENTORY_STOCK_REQUEST_ID
                AND r.IS_DELETED = 0
            WHERE r.INVENTORY_STOCK_REQUEST_ID IS NULL
        )
        BEGIN
            ROLLBACK TRANSACTION;
            SELECT (SELECT 0 AS Status, 0 AS MovementID FOR JSON PATH) AS Result;
            RETURN;
        END

        -- 3. Verify same driver and same origin
        DECLARE @DriverID NUMERIC(18,0),
                @FromLoc  NUMERIC(18,0),
                @ToLoc    NUMERIC(18,0),
                @MaxDriver NUMERIC(18,0),
                @MaxFrom   NUMERIC(18,0);

        SELECT @DriverID   = MIN(DRIVER_ID_ASSIGNED),
               @FromLoc    = MIN(FROM_INVENTORY_ID),
               @ToLoc      = MIN(INVENTORY_ID),
               @MaxDriver  = MAX(DRIVER_ID_ASSIGNED),
               @MaxFrom    = MAX(FROM_INVENTORY_ID)
        FROM INVENTORY_STOCK_REQUEST
        WHERE INVENTORY_STOCK_REQUEST_ID IN (SELECT ID FROM @ParsedIDs)
          AND IS_DELETED = 0;

        IF @DriverID IS NULL OR @DriverID != @MaxDriver
        BEGIN
            ROLLBACK TRANSACTION;
            SELECT (SELECT 0 AS Status, 0 AS MovementID FOR JSON PATH) AS Result;
            RETURN;
        END
        IF @FromLoc IS NULL OR @FromLoc != @MaxFrom
        BEGIN
            ROLLBACK TRANSACTION;
            SELECT (SELECT 0 AS Status, 0 AS MovementID FOR JSON PATH) AS Result;
            RETURN;
        END

        -- 4. All destinations must be non-NULL
        IF EXISTS (
            SELECT 1 FROM INVENTORY_STOCK_REQUEST
            WHERE INVENTORY_STOCK_REQUEST_ID IN (SELECT ID FROM @ParsedIDs)
              AND IS_DELETED = 0
              AND INVENTORY_ID IS NULL
        )
        BEGIN
            ROLLBACK TRANSACTION;
            SELECT (SELECT 0 AS Status, 0 AS MovementID FOR JSON PATH) AS Result;
            RETURN;
        END

        DECLARE @StartDate NVARCHAR(19) = CONVERT(NVARCHAR(19), GETDATE(), 120);

        -- 5. Build pipe-separated list of all distinct destinations for the NVARCHAR column
        DECLARE @AllDestinations NVARCHAR(MAX) = '';
        
        SELECT @AllDestinations = STRING_AGG(CAST(INVENTORY_ID AS NVARCHAR(20)), '|')
        FROM (
            SELECT DISTINCT INVENTORY_ID
            FROM INVENTORY_STOCK_REQUEST
            WHERE INVENTORY_STOCK_REQUEST_ID IN (SELECT ID FROM @ParsedIDs)
              AND IS_DELETED = 0
        ) AS Destinations;

        -- 6. Aggregate ALL products
        DECLARE @AggregatedProducts TABLE (
            PRODUCTS_ID NUMERIC(18,0),
            PRODUCTS_COUNT NUMERIC(18,0)
        );

        INSERT INTO @AggregatedProducts (PRODUCTS_ID, PRODUCTS_COUNT)
        SELECT r.PRODUCTS_ID,
               SUM(r.PRODUCTS_COUNT)
        FROM INVENTORY_STOCK_REQUEST r
        WHERE r.INVENTORY_STOCK_REQUEST_ID IN (SELECT ID FROM @ParsedIDs)
          AND r.IS_DELETED = 0
          AND r.PRODUCTS_COUNT > 0
        GROUP BY r.PRODUCTS_ID;

        -- 7. DUPLICATE CHECK
        IF EXISTS (
            SELECT 1
            FROM PRODUCTS_MOVEMENTS pm
            WHERE pm.DRIVERS_ID           = @DriverID
              AND pm.VEHICLE_ID           = @VehicleID
              AND pm.COMES_FROM_LOCATION_ID = @FromLoc
              AND pm.GOES_TO_LOCATION_ID   = @ToLoc
              AND pm.START_DATE_HOUR      = @StartDate
              AND pm.IS_DELETED           = 0
              AND NOT EXISTS (
                  SELECT mpl.PRODUCTS_ID, mpl.PRODUCTS_COUNT
                  FROM MOVEMENTS_PRODUCTS_LIST mpl
                  WHERE mpl.MOVEMENTS_ID = pm.PRODUCTS_MOVEMENTS_ID
                  EXCEPT
                  SELECT PRODUCTS_ID, PRODUCTS_COUNT FROM @AggregatedProducts
              )
              AND NOT EXISTS (
                  SELECT PRODUCTS_ID, PRODUCTS_COUNT FROM @AggregatedProducts
                  EXCEPT
                  SELECT mpl.PRODUCTS_ID, mpl.PRODUCTS_COUNT
                  FROM MOVEMENTS_PRODUCTS_LIST mpl
                  WHERE mpl.MOVEMENTS_ID = pm.PRODUCTS_MOVEMENTS_ID
              )
        )
        BEGIN
            ROLLBACK TRANSACTION;
            SELECT (SELECT 0 AS Status, 0 AS MovementID FOR JSON PATH) AS Result;
            RETURN;
        END

        -- 8. Create ONE movement
        INSERT INTO PRODUCTS_MOVEMENTS
            (DRIVERS_ID, VEHICLE_ID, COMES_FROM_LOCATION_ID, GOES_TO_LOCATION_ID,
             GOES_TO_LOCATION_ID_l, START_DATE_HOUR, END_DATE_HOUR, EST_ARIVAL, DID_ARIVE, IS_DELETED, IS_ACTIVE)
        VALUES
            (@DriverID, @VehicleID, @FromLoc, @ToLoc,
             @AllDestinations, @StartDate, NULL, NULL, 0, 0, 1);

        DECLARE @NewMovementID NUMERIC(18,0) = SCOPE_IDENTITY();

        -- 9. Insert aggregated products
        INSERT INTO MOVEMENTS_PRODUCTS_LIST
            (MOVEMENTS_ID, PRODUCTS_ID, PRODUCTS_COUNT)
        SELECT @NewMovementID, PRODUCTS_ID, PRODUCTS_COUNT
        FROM @AggregatedProducts;

        -- 10. Mark stock requests as deleted
        UPDATE INVENTORY_STOCK_REQUEST
        SET IS_DELETED = 1
        WHERE INVENTORY_STOCK_REQUEST_ID IN (SELECT ID FROM @ParsedIDs)
          AND IS_DELETED = 0;

        -- 11. Return success
        COMMIT TRANSACTION;
        SELECT (SELECT 1 AS Status, @NewMovementID AS MovementID FOR JSON PATH) AS Result;

    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        SELECT (SELECT 0 AS Status, 0 AS MovementID FOR JSON PATH) AS Result;
    END CATCH
END;

CREATE   PROCEDURE usp_CreateMovementFromStockRequests
    @RequestIDs NVARCHAR(MAX),      -- e.g. '1,2,3'
    @VehicleID  NUMERIC(18,0)       -- vehicle to assign to the movement
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        -- 1. Split the comma-separated IDs into a table
        DECLARE @ParsedIDs TABLE (ID NUMERIC(18,0));
        INSERT INTO @ParsedIDs (ID)
        SELECT CAST(value AS NUMERIC(18,0))
        FROM STRING_SPLIT(@RequestIDs, ',')
        WHERE RTRIM(value) <> '';

        -- 2. If nothing was passed, return 0
        IF NOT EXISTS (SELECT 1 FROM @ParsedIDs)
        BEGIN
            SELECT 0 AS Status;
            ROLLBACK TRANSACTION;
            RETURN;
        END

        -- 3. Check that every ID exists in INVENTORY_STOCK_REQUEST
        IF EXISTS (
            SELECT 1
            FROM @ParsedIDs p
            LEFT JOIN INVENTORY_STOCK_REQUEST r
                ON p.ID = r.INVENTORY_STOCK_REQUEST_ID
            WHERE r.INVENTORY_STOCK_REQUEST_ID IS NULL
        )
        BEGIN
            SELECT 0 AS Status;
            ROLLBACK TRANSACTION;
            RETURN;
        END

        -- 4. Verify same driver and same origin (DESTINATION NOT ENFORCED)
        DECLARE @DriverID NUMERIC(18,0),
                @FromLoc  NUMERIC(18,0),
                @ToLoc    NUMERIC(18,0),
                @MaxDriver NUMERIC(18,0),
                @MaxFrom   NUMERIC(18,0);

        SELECT @DriverID   = MIN(DRIVER_ID_ASSIGNED),
               @FromLoc    = MIN(FROM_INVENTORY_ID),
               @ToLoc      = MIN(INVENTORY_ID),        -- will be used as GOES_TO_LOCATION_ID
               @MaxDriver  = MAX(DRIVER_ID_ASSIGNED),
               @MaxFrom    = MAX(FROM_INVENTORY_ID)
        FROM INVENTORY_STOCK_REQUEST
        WHERE INVENTORY_STOCK_REQUEST_ID IN (SELECT ID FROM @ParsedIDs);

        IF @DriverID IS NULL OR @DriverID != @MaxDriver
        BEGIN
            SELECT 0 AS Status;
            ROLLBACK TRANSACTION;
            RETURN;
        END
        IF @FromLoc IS NULL OR @FromLoc != @MaxFrom
        BEGIN
            SELECT 0 AS Status;
            ROLLBACK TRANSACTION;
            RETURN;
        END
        -- (No check on destination – any mix is allowed)

        -- 5. Create the movement
        DECLARE @StartDate NVARCHAR(19) = CONVERT(NVARCHAR(19), GETDATE(), 120);

        INSERT INTO PRODUCTS_MOVEMENTS
            (DRIVERS_ID, VEHICLE_ID, COMES_FROM_LOCATION_ID, GOES_TO_LOCATION_ID,
             START_DATE_HOUR, END_DATE_HOUR, EST_ARIVAL, DID_ARIVE, IS_DELETED, IS_ACTIVE)
        VALUES
            (@DriverID, @VehicleID, @FromLoc, @ToLoc,
             @StartDate, NULL, NULL, 0, 0, 1);

        DECLARE @NewMovementID NUMERIC(18,0) = SCOPE_IDENTITY();

        -- 6. Insert aggregated products into MOVEMENTS_PRODUCTS_LIST
        INSERT INTO MOVEMENTS_PRODUCTS_LIST
            (MOVEMENTS_ID, PRODUCTS_ID, PRODUCTS_COUNT)
        SELECT
            @NewMovementID,
            r.PRODUCTS_ID,
            SUM(r.PRODUCTS_COUNT)
        FROM INVENTORY_STOCK_REQUEST r
        WHERE r.INVENTORY_STOCK_REQUEST_ID IN (SELECT ID FROM @ParsedIDs)
          AND r.PRODUCTS_COUNT > 0
        GROUP BY r.PRODUCTS_ID;

        -- 7. Mark the processed stock requests as deleted
        UPDATE INVENTORY_STOCK_REQUEST
        SET IS_DELETED = 1
        WHERE INVENTORY_STOCK_REQUEST_ID IN (SELECT ID FROM @ParsedIDs);

        -- 8. Success – return the new movement ID
        SELECT 1 AS Status;
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        -- On any error, return 0
        SELECT 0 AS Status;
    END CATCH
END;

CREATE   PROCEDURE [dbo].[WORK_HOUR_REPORT]
@LOGIN_SESSION NVARCHAR(512)
AS 
BEGIN
SELECT
WHRL.WORK_HOUR_REPORT_LOG_ID, 
SU.USERNAME,
TASK_NAME,
TASK_DESCRIPTION,
START_DATE_TIME,
END_DATE_TIME,
EST_HOURS_IT_WILL_TAKE,
ACTUAL_TIME_TASK_TOOK,
HOURLY_RATE_FOR_TASK,
CAST((HOURLY_RATE_FOR_TASK * ACTUAL_TIME_TASK_TOOK)AS money) AS MONEY_MADE,
SU.BASE_SALARY
FROM
WORK_HOUR_REPORT_LOG WHRL
INNER JOIN SYS_USERS SU
ON WHRL.SYS_USER_ID = SU.SYS_USER_ID
INNER JOIN TASKS T
ON T.TASKS_ID = WHRL.COMPLETED_TASK_ID
WHERE SU.LOGIN_SESSION = @LOGIN_SESSION AND END_DATE_TIME IS NOT NULL
ORDER BY END_DATE_TIME DESC
END;