USE [master]
GO
/****** Object:  Database [PROJECT_ZERO]    Script Date: 8/2/2026 2:58:40 PM ******/
CREATE DATABASE [PROJECT_ZERO]
GO
ALTER DATABASE [PROJECT_ZERO] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PROJECT_ZERO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PROJECT_ZERO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET ARITHABORT OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PROJECT_ZERO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PROJECT_ZERO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PROJECT_ZERO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PROJECT_ZERO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET RECOVERY FULL 
GO
ALTER DATABASE [PROJECT_ZERO] SET  MULTI_USER 
GO
ALTER DATABASE [PROJECT_ZERO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PROJECT_ZERO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PROJECT_ZERO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PROJECT_ZERO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PROJECT_ZERO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PROJECT_ZERO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PROJECT_ZERO] SET QUERY_STORE = ON
GO
ALTER DATABASE [PROJECT_ZERO] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PROJECT_ZERO]
GO
/****** Object:  UserDefinedFunction [dbo].[GET_USER_ID_BY_SESSION]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   FUNCTION [dbo].[GET_USER_ID_BY_SESSION]
(@LOGIN_SESSION NVARCHAR(512))
RETURNS NUMERIC
AS
BEGIN
DECLARE @RESULT NUMERIC = (SELECT TOP 1 SYS_USER_ID FROM SYS_USERS WHERE LOGIN_SESSION = @LOGIN_SESSION)
RETURN @RESULT
END
GO
/****** Object:  Table [dbo].[SYS_USERS]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_USERS](
	[SYS_USER_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[USERNAME] [nvarchar](50) NULL,
	[USER_PASSWORD] [varbinary](512) NOT NULL,
	[LOGIN_SESSION] [nvarchar](512) NULL,
	[BASE_SALARY] [decimal](6, 1) NULL,
PRIMARY KEY CLUSTERED 
(
	[SYS_USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER_LOGIN_LOG]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_LOGIN_LOG](
	[USER_LOGIN_LOG_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[SYS_USER_ID] [numeric](18, 0) NOT NULL,
	[LOGIN_DATE] [nvarchar](19) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[USER_LOGIN_LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  UserDefinedFunction [dbo].[LOGIN_LOG_SELECT]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   FUNCTION [dbo].[LOGIN_LOG_SELECT]
(
@TOKEN NVARCHAR(512)
)
RETURNS TABLE
AS
RETURN
(
	SELECT
	USER_LOGIN_LOG_ID, USERNAME, LOGIN_DATE
	FROM USER_LOGIN_LOG ULL
	INNER JOIN
	SYS_USERS SU
	ON ULL.SYS_USER_ID = SU.SYS_USER_ID
	WHERE SU.LOGIN_SESSION = @TOKEN
)
GO
/****** Object:  Table [dbo].[LT_ROLES]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LT_ROLES](
	[ROLES_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[ROLE_CODE] [numeric](18, 0) NOT NULL,
	[ROLES_TITLE] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROLES_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ROLE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ROLES_TITLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS_ROLES]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS_ROLES](
	[USERS_ROLES_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[SYS_USER_ID] [numeric](18, 0) NOT NULL,
	[ROLE_CODE] [numeric](18, 0) NOT NULL,
	[ASSIGNMENT_DATE] [nvarchar](19) NULL,
	[REVOKE_DATE] [nvarchar](19) NULL,
	[IS_ACTIVE] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[USERS_ROLES_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_USERS_ROLES_USER_ROLE] UNIQUE NONCLUSTERED 
(
	[SYS_USER_ID] ASC,
	[ROLE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  UserDefinedFunction [dbo].[ROLES_LOG_SELECT]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   FUNCTION [dbo].[ROLES_LOG_SELECT]
(
@TOKEN NVARCHAR(512)
)
RETURNS TABLE
AS
RETURN
(
	SELECT
	UR.USERS_ROLES_ID,
	LR.ROLES_TITLE,
	UR.ASSIGNMENT_DATE
	FROM USERS_ROLES UR
	INNER JOIN
	SYS_USERS SU
	ON UR.SYS_USER_ID = SU.SYS_USER_ID
	INNER JOIN LT_ROLES LR
	ON UR.ROLE_CODE = LR.ROLE_CODE
	WHERE (SU.LOGIN_SESSION = @TOKEN) AND UR.IS_ACTIVE = 1
)
GO
/****** Object:  Table [dbo].[ACTIVITY_LOG]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACTIVITY_LOG](
	[ACTIVITY_LOG_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[SYS_USER_ID] [numeric](18, 0) NOT NULL,
	[ACTIVITY_REMARKS] [nvarchar](300) NULL,
	[DATE_TIME] [nvarchar](19) NULL,
PRIMARY KEY CLUSTERED 
(
	[ACTIVITY_LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_CALL_ACCESS]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_CALL_ACCESS](
	[SYS_CALL_ACCESS_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[ROLE_CODE] [numeric](18, 0) NULL,
	[CAN_READ] [bit] NULL,
	[CAN_WRITE] [bit] NULL,
	[SYS_OBJECT_CODE] [numeric](18, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[SYS_CALL_ACCESS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_OBJECTS]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_OBJECTS](
	[SYS_OBJECT_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[SYS_OBJECT_NAME] [nvarchar](50) NOT NULL,
	[SYS_OBJECT_CODE] [numeric](18, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SYS_OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TASKS]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TASKS](
	[TASKS_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[TASK_NAME] [nvarchar](30) NULL,
	[TASK_DESCRIPTION] [nvarchar](300) NULL,
	[TASK_FOR_ROLE_ID] [numeric](18, 0) NULL,
	[START_DATE_TIME] [nvarchar](19) NULL,
	[END_DATE_TIME] [nvarchar](19) NULL,
	[ACCEPTED_BY_SYS_USER_ID] [numeric](18, 0) NULL,
	[EST_HOURS_IT_WILL_TAKE] [decimal](6, 2) NULL,
	[ACTUAL_TIME_TASK_TOOK] [decimal](6, 2) NULL,
	[HOURLY_RATE_FOR_TASK] [decimal](6, 2) NULL,
	[TASK_CREATED_BY_SYS_USER_ID] [numeric](18, 0) NOT NULL,
	[CREATED_DATE] [nvarchar](19) NULL,
PRIMARY KEY CLUSTERED 
(
	[TASKS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WORK_HOUR_REPORT_LOG]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WORK_HOUR_REPORT_LOG](
	[WORK_HOUR_REPORT_LOG_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[SYS_USER_ID] [numeric](18, 0) NOT NULL,
	[COMPLETED_TASK_ID] [numeric](18, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_HOUR_REPORT_LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASKS]  WITH CHECK ADD CHECK  (([ACTUAL_TIME_TASK_TOOK]>(0)))
GO
ALTER TABLE [dbo].[TASKS]  WITH CHECK ADD CHECK  (([EST_HOURS_IT_WILL_TAKE]>(0)))
GO
ALTER TABLE [dbo].[TASKS]  WITH CHECK ADD CHECK  (([HOURLY_RATE_FOR_TASK]>(0)))
GO
/****** Object:  StoredProcedure [dbo].[ACTIVITY_LOG_MANAGER]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[ACTIVITY_LOG_MANAGER]
@READ_ONLY BIT = 1
,@LOGGIN_SESSION NVARCHAR(512) = NULL
,@ACTIVITY_REMARK NVARCHAR(300) = NULL
AS
BEGIN

	DECLARE @SYS_USER_ID NUMERIC = (SELECT TOP 1 SYS_USER_ID FROM SYS_USERS WHERE LOGIN_SESSION = @LOGGIN_SESSION)

	IF @READ_ONLY = 0
	BEGIN
		
		INSERT INTO ACTIVITY_LOG
		(
		SYS_USER_ID,
		ACTIVITY_REMARKS,
		DATE_TIME
		)
		VALUES
		(
		@SYS_USER_ID,
		@ACTIVITY_REMARK,
		CONVERT(NVARCHAR(19), GETDATE(), 120)
		)
		SELECT 1 AS STATUS
	END
	ELSE
	BEGIN

		SELECT ACTIVITY_LOG_ID, AL.SYS_USER_ID, USERNAME, AL.ACTIVITY_REMARKS, DATE_TIME FROM ACTIVITY_LOG AL INNER JOIN SYS_USERS SU ON AL.SYS_USER_ID = SU.SYS_USER_ID 

	END
END
GO
/****** Object:  StoredProcedure [dbo].[CHANGE_PASSWORD]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[CHANGE_PASSWORD]
@NEW_PASSWORD NVARCHAR(50),
@OLD_PASSWORD NVARCHAR(50),
@LOGIN_SESSION NVARCHAR(512)
AS
BEGIN
	IF EXISTS(SELECT 1 FROM SYS_USERS WHERE LOGIN_SESSION = @LOGIN_SESSION AND USER_PASSWORD = HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @OLD_PASSWORD, N'4THEYS123#AYIMJO31SEPHSEED')))
	BEGIN
		UPDATE SYS_USERS
		SET
		USER_PASSWORD = HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @NEW_PASSWORD, N'4THEYS123#AYIMJO31SEPHSEED'))
		WHERE LOGIN_SESSION = @LOGIN_SESSION
		SELECT 1 AS STATUS
		EXEC ACTIVITY_LOG_MANAGER 0, @LOGIN_SESSION, N'USER SUCCESSFULLY CHANGED PASSWORD'
	END
	ELSE
	BEGIN
	SELECT 0 AS STATUS
		EXEC ACTIVITY_LOG_MANAGER 0, @LOGIN_SESSION, N'USER TRIED AND FAILED TO CHANGE PASSWORD'
	END
END
GO
/****** Object:  StoredProcedure [dbo].[CHANGE_USER_CRED_BY_ADMIN]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[CHANGE_USER_CRED_BY_ADMIN]
@SYS_USER_ID NUMERIC,
@CHANGE_PASSWORD BIT,
@CHANGED_DATA NVARCHAR(100)
AS
BEGIN

	IF @CHANGE_PASSWORD = 1
		BEGIN
			UPDATE SYS_USERS 
			SET 
			USER_PASSWORD = HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @CHANGED_DATA, N'4THEYS123#AYIMJO31SEPHSEED'))
			WHERE SYS_USER_ID = @SYS_USER_ID
		END
	ELSE
		BEGIN
			UPDATE SYS_USERS 
			SET 
			USERNAME = @CHANGED_DATA
			WHERE SYS_USER_ID = @SYS_USER_ID
		END
		SELECT 1 AS STATUS
END
GO
/****** Object:  StoredProcedure [dbo].[CHANGE_USERNAME]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[CHANGE_USERNAME]
@NEW_USERNAME NVARCHAR(50),
@LOGIN_SESSION NVARCHAR(512)
AS
BEGIN
	UPDATE SYS_USERS SET USERNAME = @NEW_USERNAME WHERE LOGIN_SESSION = @LOGIN_SESSION
	EXEC ACTIVITY_LOG_MANAGER 0, @LOGIN_SESSION, N'USER SUCCESSFULLY CHANGED THEIR USERNAME'
	SELECT 1 AS STATUS
END
GO
/****** Object:  StoredProcedure [dbo].[CREATE_UPDATE_DELETE_ROLES]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[CREATE_UPDATE_DELETE_ROLES]
@ACTION_NAME NVARCHAR(20),
@ROLE_CODE NUMERIC = 0,
@ROLE_NAME NVARCHAR(50) = NULL,
@SYS_OBJECT_NAME NVARCHAR(50) = NULL,
@CAN_READ BIT = 0,
@CAN_WRITE BIT = 0
AS
BEGIN
DECLARE @OBJECT_CODE NUMERIC = (SELECT TOP 1 SYS_OBJECT_CODE FROM SYS_OBJECTS WHERE SYS_OBJECT_NAME = @SYS_OBJECT_NAME)
	IF LOWER(@ACTION_NAME) = LOWER(N'DELETE_ROLE') AND NOT @ROLE_CODE = 0
		BEGIN
			DELETE FROM SYS_CALL_ACCESS WHERE ROLE_CODE = @ROLE_CODE
			DELETE FROM LT_ROLES WHERE ROLE_CODE = @ROLE_CODE
		END
	ELSE IF LOWER(@ACTION_NAME) = LOWER(N'CREATE_ROLE') AND @ROLE_NAME IS NOT NULL
			AND NOT EXISTS(SELECT 1 FROM LT_ROLES WHERE ROLE_CODE = @ROLE_CODE)
		BEGIN
			INSERT INTO LT_ROLES (ROLE_CODE, ROLES_TITLE) VALUES (@ROLE_CODE, @ROLE_NAME)
		END
	ELSE IF LOWER(@ACTION_NAME) = LOWER(N'UPDATE_ROLE') AND NOT @ROLE_CODE = 0
		BEGIN
			UPDATE LT_ROLES SET ROLES_TITLE = @ROLE_NAME WHERE ROLE_CODE = @ROLE_CODE
		END
	ELSE IF LOWER(@ACTION_NAME) = LOWER(N'ADD_PERMISSION') AND NOT @ROLE_CODE = 0 AND @SYS_OBJECT_NAME IS NOT NULL
			AND EXISTS(SELECT TOP 1 1 FROM SYS_OBJECTS WHERE SYS_OBJECT_NAME = @SYS_OBJECT_NAME)
			AND EXISTS(SELECT TOP 1 1 FROM LT_ROLES WHERE ROLE_CODE = @ROLE_CODE)
		BEGIN
			IF NOT EXISTS(SELECT 1 FROM SYS_CALL_ACCESS WHERE SYS_OBJECT_CODE = @OBJECT_CODE AND ROLE_CODE = @ROLE_CODE)
				BEGIN
					INSERT INTO SYS_CALL_ACCESS (ROLE_CODE, SYS_OBJECT_CODE, CAN_READ, CAN_WRITE) VALUES (@ROLE_CODE, @OBJECT_CODE, @CAN_READ, @CAN_WRITE)
				END
			ELSE
				BEGIN
					UPDATE SYS_CALL_ACCESS
					SET
						CAN_READ = @CAN_READ,
						CAN_WRITE = @CAN_WRITE
						WHERE SYS_OBJECT_CODE = @OBJECT_CODE AND ROLE_CODE = @ROLE_CODE
				END
		END
	ELSE IF LOWER(@ACTION_NAME) = LOWER(N'DELETE_PERMISSION') AND NOT @ROLE_CODE = 0 AND @SYS_OBJECT_NAME IS NOT NULL
		BEGIN
			DELETE FROM SYS_CALL_ACCESS WHERE SYS_OBJECT_CODE = @OBJECT_CODE AND ROLE_CODE = @ROLE_CODE
		END

	SELECT 1 AS STATUS
END
GO
/****** Object:  StoredProcedure [dbo].[IS_ALLOWED]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[IS_ALLOWED]
@LOGIN_SESSION NVARCHAR(512),
@SYS_OBJECT_CODE NUMERIC
AS
BEGIN

	IF EXISTS (SELECT 1 FROM SYS_CALL_ACCESS WHERE SYS_OBJECT_CODE = @SYS_OBJECT_CODE AND ROLE_CODE IN
	(SELECT ROLE_CODE FROM USERS_ROLES WHERE ISNULL(IS_ACTIVE ,1) = 1 AND SYS_USER_ID = 
	(SELECT SYS_USER_ID FROM SYS_USERS WHERE LOGIN_SESSION = @LOGIN_SESSION)))
	BEGIN
		SELECT 1 AS RESULT
	END
	ELSE
	BEGIN
		SELECT 0 AS RESULT
	END
END
GO
/****** Object:  StoredProcedure [dbo].[IS_ALLOWED_READ]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[IS_ALLOWED_READ]
@LOGIN_SESSION NVARCHAR(512),
@SYS_OBJECT_CODE NUMERIC
AS
BEGIN

	IF EXISTS (SELECT 1 FROM SYS_CALL_ACCESS WHERE CAN_READ = 1 AND SYS_OBJECT_CODE = @SYS_OBJECT_CODE AND ROLE_CODE IN
	(SELECT ROLE_CODE FROM USERS_ROLES WHERE ISNULL(IS_ACTIVE ,1) = 1 AND SYS_USER_ID = 
	(SELECT SYS_USER_ID FROM SYS_USERS WHERE LOGIN_SESSION = @LOGIN_SESSION)))
	BEGIN
		SELECT 1 AS RESULT
	END
	ELSE
	BEGIN
		SELECT 0 AS RESULT
	END
END
GO
/****** Object:  StoredProcedure [dbo].[IS_AUTHENTICATED]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[IS_AUTHENTICATED]	
@TOKEN NVARCHAR(MAX)
AS
BEGIN
	SELECT TOP 1
	CASE
	WHEN EXISTS(SELECT 1 FROM SYS_USERS WHERE LOGIN_SESSION = @TOKEN)
	THEN
	1
	ELSE
	0 
	END AS RESULT
	FROM SYS_USERS
END
GO
/****** Object:  StoredProcedure [dbo].[LOGIN_VALID]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[LOGIN_VALID]
@USERNAME NVARCHAR(50),
@PASSWORD NVARCHAR(50)
AS
BEGIN
DECLARE @USER_ID NUMERIC = (SELECT SYS_USER_ID FROM SYS_USERS WHERE LOWER(USERNAME) = LOWER(@USERNAME) AND USER_PASSWORD = HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @PASSWORD, N'4THEYS123#AYIMJO31SEPHSEED')));
	IF @USER_ID IS NOT NULL
	BEGIN
		DECLARE @TOKENVARBINARY VARBINARY(512)
		SET @TOKENVARBINARY = HASHBYTES('SHA2_512', CONCAT(N'I%@MBAR#4BI$GI$RL', @USERNAME, N'4THEYS123#AYIMJO31SEPHSEED', CAST(GETUTCDATE() AS NVARCHAR)))
		
		DECLARE @TOKEN NVARCHAR(512) = CONVERT(NVARCHAR(512), @TOKENVARBINARY, 2);
		
		UPDATE SYS_USERS
		SET
		LOGIN_SESSION = @TOKEN
		WHERE SYS_USER_ID = @USER_ID

		INSERT INTO USER_LOGIN_LOG (SYS_USER_ID, LOGIN_DATE) VALUES (@USER_ID, CONVERT(NVARCHAR(19), GETDATE(), 120))
		
		SELECT 1 AS RESULT, @TOKEN AS TOKEN
	END
	ELSE
	SELECT 0 AS RESULT, N'' AS TOKEN
END
GO
/****** Object:  StoredProcedure [dbo].[ROLES_MANAGEMENT]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[ROLES_MANAGEMENT] 
@USERNAME NVARCHAR(50),
@ROLES_TITLE NVARCHAR(50),
@REVOKE BIT = 0
AS
BEGIN

DECLARE @SYS_USER_ID NUMERIC = (SELECT TOP 1 SYS_USER_ID FROM SYS_USERS WHERE LOWER(USERNAME) LIKE LOWER(@USERNAME))
DECLARE @ROLE_CODE NUMERIC = (SELECT TOP 1 ROLE_CODE FROM LT_ROLES WHERE LOWER(ROLES_TITLE) LIKE LOWER(@ROLES_TITLE))
DECLARE @EXISTS BIT = 0;

IF EXISTS( SELECT 1 FROM USERS_ROLES WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE)
BEGIN
SET @EXISTS = 1
END

IF @SYS_USER_ID IS NOT NULL AND @ROLE_CODE IS NOT NULL
	BEGIN
	IF NOT(@REVOKE = 1)
		BEGIN
		IF @EXISTS = 1
			BEGIN
			
			UPDATE USERS_ROLES SET IS_ACTIVE = 1 WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE
			END
		ELSE
			BEGIN
			
			INSERT INTO USERS_ROLES (SYS_USER_ID, ROLE_CODE, ASSIGNMENT_DATE, IS_ACTIVE) VALUES (@SYS_USER_ID, @ROLE_CODE, CONVERT(NVARCHAR(19), GETDATE(), 120), 1)
			END
		END
	ELSE
		BEGIN
		
		IF @EXISTS = 1
		UPDATE USERS_ROLES SET IS_ACTIVE = 0 WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE
		END
	END

	SELECT 1 AS STATUS
	
END
GO
/****** Object:  StoredProcedure [dbo].[ROLES_MANAGEMENT_ID_BASED]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE     PROCEDURE [dbo].[ROLES_MANAGEMENT_ID_BASED] 
@REVOKE BIT = 0,
@SYS_USER_ID NUMERIC,
@ROLE_CODE NUMERIC
AS
BEGIN

DECLARE @EXISTS BIT = 0;
IF EXISTS( SELECT 1 FROM USERS_ROLES WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE)
BEGIN
SET @EXISTS = 1
END

IF @SYS_USER_ID IS NOT NULL AND @ROLE_CODE IS NOT NULL
	BEGIN
	IF NOT(@REVOKE = 1)
		BEGIN
		IF @EXISTS = 1
			BEGIN
			UPDATE USERS_ROLES SET IS_ACTIVE = 1 WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE
			
			END
		ELSE
			BEGIN
			INSERT INTO USERS_ROLES (SYS_USER_ID, ROLE_CODE, ASSIGNMENT_DATE, IS_ACTIVE) VALUES (@SYS_USER_ID, @ROLE_CODE, CONVERT(NVARCHAR(19), GETDATE(), 120), 1)
			
			END
		END
	ELSE
		BEGIN
		
		IF @EXISTS = 1
		UPDATE USERS_ROLES SET IS_ACTIVE = 0 WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE
		END
	END
	SELECT 1 AS STATUS
END
GO
/****** Object:  StoredProcedure [dbo].[SIGNUP_NEWUSER]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[SIGNUP_NEWUSER]
@USERNAME NVARCHAR(50),
@PASSWORD NVARCHAR(100)
AS
BEGIN
  IF NOT EXISTS(SELECT 1 FROM SYS_USERS WHERE LOWER(USERNAME) LIKE LOWER(@USERNAME))
  BEGIN
  INSERT INTO [SYS_USERS]
  (
  [USERNAME],
  USER_PASSWORD
  )
  VALUES
  (
  LOWER(@USERNAME),
  HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @PASSWORD, N'4THEYS123#AYIMJO31SEPHSEED'))
  )
  SELECT 1 AS RESULT
  END
  ELSE
  BEGIN
  SELECT 0 AS RESULT
  END
END
GO
/****** Object:  StoredProcedure [dbo].[TASKS_REPORT]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[TASKS_REPORT]
@BY_USER_SESSION NVARCHAR(512) = NULL,
@TASK_ID_ACCPETED NUMERIC = NULL,
@END_TASK BIT = NULL
AS
BEGIN
BEGIN TRANSACTION
--DECLARE @TEMP NVARCHAR(MAX)
IF @TASK_ID_ACCPETED IS NOT NULL AND @BY_USER_SESSION IS NOT NULL AND EXISTS(SELECT 1 FROM TASKS WHERE TASKS_ID = @TASK_ID_ACCPETED) AND NOT @END_TASK = 1
BEGIN
BEGIN TRY
UPDATE TASKS
SET
ACCEPTED_BY_SYS_USER_ID = DBO.GET_USER_ID_BY_SESSION(@BY_USER_SESSION),
START_DATE_TIME = CONVERT(NVARCHAR(19), GETDATE(), 120)
WHERE TASKS_ID = @TASK_ID_ACCPETED
--SET @TEMP = (N'USER ACCEPTED A TASK WITH TASK ID : ' + @TASK_ID_ACCPETED)
--EXEC ACTIVITY_LOG_MANAGER 0, @BY_USER_SESSION, @TEMP
END TRY
BEGIN CATCH
ROLLBACK;
END CATCH
END

IF @END_TASK = 1
BEGIN
BEGIN TRY
UPDATE TASKS
SET
END_DATE_TIME = CONVERT(NVARCHAR(19), GETDATE(), 120),
ACTUAL_TIME_TASK_TOOK = (SELECT TOP 1 DATEDIFF(
    SECOND,
    CONVERT(DATETIME, START_DATE_TIME),
    CONVERT(DATETIME, CONVERT(NVARCHAR(19), GETDATE(), 120))
) AS HoursDifference FROM TASKS WHERE TASKS_ID = @TASK_ID_ACCPETED) / 3600.0
WHERE TASKS_ID = @TASK_ID_ACCPETED

INSERT INTO WORK_HOUR_REPORT_LOG
(SYS_USER_ID, COMPLETED_TASK_ID)
VALUES
((SELECT TOP 1 SYS_USER_ID FROM SYS_USERS WHERE LOGIN_SESSION = @BY_USER_SESSION) ,@TASK_ID_ACCPETED)
--SET @TEMP = (N'USER ENDED A TASK WITH TASK ID : ' + @TASK_ID_ACCPETED)
--EXEC ACTIVITY_LOG_MANAGER 0, @BY_USER_SESSION, @TEMP
END TRY
BEGIN CATCH
ROLLBACK;
END CATCH
END

SELECT 
TASKS_ID,
TASK_NAME,
TASK_DESCRIPTION,
CASE
WHEN START_DATE_TIME IS NULL
THEN N'No one has accepted this task yet'
ELSE
START_DATE_TIME
END AS START_DATE_TIME
,
CASE
WHEN START_DATE_TIME IS NULL
THEN N'No one has finished this task yet'
ELSE
END_DATE_TIME
END AS END_DATE_TIME
,EST_HOURS_IT_WILL_TAKE
,HOURLY_RATE_FOR_TASK
,SU.USERNAME AS TASK_CREATED_BY
FROM TASKS T
INNER JOIN SYS_USERS SU
ON SU.SYS_USER_ID = T.TASK_CREATED_BY_SYS_USER_ID
COMMIT

END
GO
/****** Object:  StoredProcedure [dbo].[WORK_HOUR_REPORT]    Script Date: 8/2/2026 2:58:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[WORK_HOUR_REPORT]
@LOGIN_SESSION NVARCHAR(512)
AS 
BEGIN
SELECT
WHRL.WORK_HOUR_REPORT_LOG_ID, 
SU.USERNAME,
TASK_NAME,
TASK_DESCRIPTION,
START_DATE_TIME,
END_DATE_TIME,
EST_HOURS_IT_WILL_TAKE,
ACTUAL_TIME_TASK_TOOK,
HOURLY_RATE_FOR_TASK,
CAST((HOURLY_RATE_FOR_TASK * ACTUAL_TIME_TASK_TOOK)AS money) AS MONEY_MADE,
SU.BASE_SALARY
FROM
WORK_HOUR_REPORT_LOG WHRL
INNER JOIN SYS_USERS SU
ON WHRL.SYS_USER_ID = SU.SYS_USER_ID
INNER JOIN TASKS T
ON T.TASKS_ID = WHRL.COMPLETED_TASK_ID
WHERE SU.LOGIN_SESSION = @LOGIN_SESSION AND END_DATE_TIME IS NOT NULL
ORDER BY END_DATE_TIME DESC
END
GO
USE [master]
GO
ALTER DATABASE [PROJECT_ZERO] SET  READ_WRITE 
GO
