-- =====================================================================
-- Script: Full Reset and Creation for PROJECT_ZERO Database
-- Description: Drops and recreates the database, creates all tables,
--              functions, and stored procedures in the correct order.
-- =====================================================================

-- Drop database if it exists (to ensure a clean environment)
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'PROJECT_ZERO')
BEGIN
    ALTER DATABASE PROJECT_ZERO SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE PROJECT_ZERO;
END
GO

-- Create database
CREATE DATABASE PROJECT_ZERO;
GO

-- Use the new database
USE PROJECT_ZERO;
GO

-- ---------------------------------------------------------------------
-- Create schema (dbo is default, but we ensure it exists)
-- ---------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'dbo')
BEGIN
    EXEC('CREATE SCHEMA dbo');
END
GO

-- =====================================================================
-- TABLE CREATION (ordered to satisfy foreign key dependencies)
-- =====================================================================

-- 1. LT_INVENTORY_LOCATION_TYPE
CREATE TABLE dbo.LT_INVENTORY_LOCATION_TYPE (
    LT_INVENTORY_LOCATION_TYPE_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    INVENTORY_LOCATION_TYPE_TITLE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IS_DELETED bit NULL,
    CONSTRAINT PK__LT_INVEN__8701A02787ECB33A PRIMARY KEY (LT_INVENTORY_LOCATION_TYPE_ID)
);
GO

-- 2. PRODUCTS_CATEGORY
CREATE TABLE dbo.PRODUCTS_CATEGORY (
    PRODUCTS_CATEGORY_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    PRODUCTS_CATEGORY_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IS_DELETED bit NULL,
    CONSTRAINT PK__PRODUCTS__F1C1E23B2B52B202 PRIMARY KEY (PRODUCTS_CATEGORY_ID)
);
GO

-- 3. LT_ROLES
CREATE TABLE dbo.LT_ROLES (
    ROLES_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    ROLE_CODE numeric(18,0) NOT NULL,
    ROLES_TITLE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    CONSTRAINT PK__LT_ROLES__A24FBB16DE01410D PRIMARY KEY (ROLES_ID),
    CONSTRAINT UQ__LT_ROLES__20BB649DA1B5E8E4 UNIQUE (ROLE_CODE),
    CONSTRAINT UQ__LT_ROLES__676386A8B59F4AF1 UNIQUE (ROLES_TITLE)
);
GO

-- 4. SYS_OBJECTS
CREATE TABLE dbo.SYS_OBJECTS (
    SYS_OBJECT_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    SYS_OBJECT_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    SYS_OBJECT_CODE numeric(18,0) NOT NULL,
    CONSTRAINT PK__SYS_OBJE__0F9D6F19F8515390 PRIMARY KEY (SYS_OBJECT_ID)
);
GO

-- 5. SYS_USERS
CREATE TABLE dbo.SYS_USERS (
    SYS_USER_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    USERNAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    USER_PASSWORD varbinary(512) NOT NULL,
    LOGIN_SESSION nvarchar(512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    BASE_SALARY decimal(6,1) NULL,
    CONSTRAINT PK__SYS_USER__2B4E4E5C292644C2 PRIMARY KEY (SYS_USER_ID)
);
GO

-- 6. VEHICLE
CREATE TABLE dbo.VEHICLE (
    VEHICLE_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    VEHICLE_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    VEHICLE_LICENCE_PLATE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IS_DELETED bit NULL,
    CONSTRAINT PK__VEHICLE__7F2CA3502CF00E2C PRIMARY KEY (VEHICLE_ID)
);
GO

-- 7. FLEET_TEAMS
CREATE TABLE dbo.FLEET_TEAMS (
    FLEET_TEAM_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    FLEET_TEAM_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    DESCRIPTION nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IS_DELETED bit NULL,
    CONSTRAINT PK__FLEET_TE__906FB8ACBEDAF0F7 PRIMARY KEY (FLEET_TEAM_ID)
);
GO

-- 8. DRIVERS (references FLEET_TEAMS, but no FK constraint; we create after FLEET_TEAMS)
CREATE TABLE dbo.DRIVERS (
    DRIVER_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    DRIVER_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    DRIVER_LAST_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    DRIVERS_NATIONAL_CODE nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    DRIVERS_PHONE_NUMBER nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IS_DELETED bit NULL,
    FLEET_TEAM_ID numeric(18,0) NULL,
    CONSTRAINT PK__DRIVERS__030E1394EC67E358 PRIMARY KEY (DRIVER_ID),
    CONSTRAINT UQ_DRIVERS_NATIONAL_CODE UNIQUE (DRIVERS_NATIONAL_CODE),
    CONSTRAINT UQ_DRIVERS_PHONE UNIQUE (DRIVERS_PHONE_NUMBER)
);
GO

-- 9. INVENTORY_LOCATION (references LT_INVENTORY_LOCATION_TYPE)
CREATE TABLE dbo.INVENTORY_LOCATION (
    INVENTORY_LOCATION_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    INVENTORY_LOCATION_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    INVENTORY_LOCATION_ADDRESS nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    INVENTORY_LOCATION_LAT decimal(9,6) NOT NULL,
    INVENTORY_LOCATION_LONG decimal(9,6) NOT NULL,
    LT_INVENTORY_LOCATION_TYPE_ID numeric(18,0) NOT NULL,
    IS_DELETED bit NULL,
    CONSTRAINT PK__INVENTOR__725D6AEFDB040A7E PRIMARY KEY (INVENTORY_LOCATION_ID),
    CONSTRAINT UQ_INVENTORY_LOCATION UNIQUE (INVENTORY_LOCATION_NAME,INVENTORY_LOCATION_ADDRESS,INVENTORY_LOCATION_LAT,INVENTORY_LOCATION_LONG),
    CONSTRAINT FK__INVENTORY__LT_IN__0C85DE4D FOREIGN KEY (LT_INVENTORY_LOCATION_TYPE_ID)
        REFERENCES dbo.LT_INVENTORY_LOCATION_TYPE(LT_INVENTORY_LOCATION_TYPE_ID)
);
GO

-- 10. PRODUCTS (references PRODUCTS_CATEGORY)
CREATE TABLE dbo.PRODUCTS (
    PRODUCTS_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    PRODUCTS_NAME nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    PRODUCTS_CATEGORY_ID numeric(18,0) NULL,
    IS_DELETED bit NULL,
    CONSTRAINT PK__PRODUCTS__3F2458C776019CD0 PRIMARY KEY (PRODUCTS_ID),
    CONSTRAINT FK__PRODUCTS__PRODUC__06CD04F7 FOREIGN KEY (PRODUCTS_CATEGORY_ID)
        REFERENCES dbo.PRODUCTS_CATEGORY(PRODUCTS_CATEGORY_ID)
);
GO

-- 11. PRODUCTS_STOCKS (references PRODUCTS and INVENTORY_LOCATION)
CREATE TABLE dbo.PRODUCTS_STOCKS (
    PRODUCTS_STOCKS_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    PRODUCTS_ID numeric(18,0) NOT NULL,
    INVENTORY_LOCATION_ID numeric(18,0) NOT NULL,
    PRODUCT_COUNT_IN_STOCK numeric(18,0) NULL,
    CONSTRAINT PK__PRODUCTS__00BE76EAC838822B PRIMARY KEY (PRODUCTS_STOCKS_ID),
    CONSTRAINT UQ_PRODUCT_LOCATION UNIQUE (PRODUCTS_ID,INVENTORY_LOCATION_ID),
    CONSTRAINT FK__PRODUCTS___INVEN__114A936A FOREIGN KEY (INVENTORY_LOCATION_ID)
        REFERENCES dbo.INVENTORY_LOCATION(INVENTORY_LOCATION_ID),
    CONSTRAINT FK__PRODUCTS___PRODU__10566F31 FOREIGN KEY (PRODUCTS_ID)
        REFERENCES dbo.PRODUCTS(PRODUCTS_ID),
    CONSTRAINT CK__PRODUCTS___PRODU__123EB7A3 CHECK (PRODUCT_COUNT_IN_STOCK >= 0)
);
GO

-- 12. PRODUCTS_MOVEMENTS (references DRIVERS, VEHICLE, INVENTORY_LOCATION)
CREATE TABLE dbo.PRODUCTS_MOVEMENTS (
    PRODUCTS_MOVEMENTS_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    DRIVERS_ID numeric(18,0) NOT NULL,
    VEHICLE_ID numeric(18,0) NOT NULL,
    COMES_FROM_LOCATION_ID numeric(18,0) NOT NULL,
    GOES_TO_LOCATION_ID numeric(18,0) NOT NULL,
    START_DATE_HOUR nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    END_DATE_HOUR nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    EST_ARIVAL nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    DID_ARIVE bit NULL,
    IS_DELETED bit NULL,
    IS_ACTIVE bit NULL,
    CONSTRAINT PK__PRODUCTS__077925396FDD356B PRIMARY KEY (PRODUCTS_MOVEMENTS_ID),
    CONSTRAINT FK__PRODUCTS___COMES__1AD3FDA4 FOREIGN KEY (COMES_FROM_LOCATION_ID)
        REFERENCES dbo.INVENTORY_LOCATION(INVENTORY_LOCATION_ID),
    CONSTRAINT FK__PRODUCTS___DRIVE__18EBB532 FOREIGN KEY (DRIVERS_ID)
        REFERENCES dbo.DRIVERS(DRIVER_ID),
    CONSTRAINT FK__PRODUCTS___GOES___1BC821DD FOREIGN KEY (GOES_TO_LOCATION_ID)
        REFERENCES dbo.INVENTORY_LOCATION(INVENTORY_LOCATION_ID),
    CONSTRAINT FK__PRODUCTS___VEHIC__19DFD96B FOREIGN KEY (VEHICLE_ID)
        REFERENCES dbo.VEHICLE(VEHICLE_ID)
);
GO

-- 13. MOVEMENTS_PRODUCTS_LIST (references PRODUCTS_MOVEMENTS and PRODUCTS)
CREATE TABLE dbo.MOVEMENTS_PRODUCTS_LIST (
    MOVEMENTS_PRODUCTS_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    MOVEMENTS_ID numeric(18,0) NOT NULL,
    PRODUCTS_ID numeric(18,0) NOT NULL,
    PRODUCTS_COUNT numeric(18,0) NULL,
    CONSTRAINT PK__MOVEMENT__15D0A82D5D055CBE PRIMARY KEY (MOVEMENTS_PRODUCTS_ID),
    CONSTRAINT FK__MOVEMENTS__MOVEM__1EA48E88 FOREIGN KEY (MOVEMENTS_ID)
        REFERENCES dbo.PRODUCTS_MOVEMENTS(PRODUCTS_MOVEMENTS_ID),
    CONSTRAINT FK__MOVEMENTS__PRODU__1F98B2C1 FOREIGN KEY (PRODUCTS_ID)
        REFERENCES dbo.PRODUCTS(PRODUCTS_ID),
    CONSTRAINT CK__MOVEMENTS__PRODU__208CD6FA CHECK (PRODUCTS_COUNT > 0)
);
GO

-- 14. ACTIVITY_LOG
CREATE TABLE dbo.ACTIVITY_LOG (
    ACTIVITY_LOG_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    SYS_USER_ID numeric(18,0) NOT NULL,
    ACTIVITY_REMARKS nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    DATE_TIME nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONSTRAINT PK__ACTIVITY__CB0ACC226E441539 PRIMARY KEY (ACTIVITY_LOG_ID)
);
GO

-- 15. INVENTORY_STOCK_REQUEST
CREATE TABLE dbo.INVENTORY_STOCK_REQUEST (
    INVENTORY_STOCK_REQUEST_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    INVENTORY_ID numeric(18,0) NULL,
    FROM_INVENTORY_ID numeric(18,0) NULL,
    PRODUCTS_ID numeric(18,0) NULL,
    IS_GET bit NULL,
    IS_DELETED bit NULL,
    PRODUCTS_COUNT numeric(18,0) NULL,
    ACCEPT_BY_INVENTORY_ID numeric(18,0) NULL,
    DRIVER_ID_ASSIGNED numeric(18,0) NULL,
    CONSTRAINT PK__INVENTOR__A4D2D9FDA25BE1CB PRIMARY KEY (INVENTORY_STOCK_REQUEST_ID)
);
GO

-- 16. SYS_CALL_ACCESS
CREATE TABLE dbo.SYS_CALL_ACCESS (
    SYS_CALL_ACCESS_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    ROLE_CODE numeric(18,0) NULL,
    CAN_READ bit NULL,
    CAN_WRITE bit NULL,
    SYS_OBJECT_CODE numeric(18,0) NULL,
    CONSTRAINT PK__SYS_CALL__1C5DECD0FC7E5667 PRIMARY KEY (SYS_CALL_ACCESS_ID)
);
GO

-- 17. TASKS
CREATE TABLE dbo.TASKS (
    TASKS_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    TASK_NAME nvarchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    TASK_DESCRIPTION nvarchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    TASK_FOR_ROLE_ID numeric(18,0) NULL,
    START_DATE_TIME nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    END_DATE_TIME nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    ACCEPTED_BY_SYS_USER_ID numeric(18,0) NULL,
    EST_HOURS_IT_WILL_TAKE decimal(6,2) NULL,
    ACTUAL_TIME_TASK_TOOK decimal(6,2) NULL,
    HOURLY_RATE_FOR_TASK decimal(6,2) NULL,
    TASK_CREATED_BY_SYS_USER_ID numeric(18,0) NOT NULL,
    CREATED_DATE nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONSTRAINT PK__TASKS__A00C07A49D8AAB71 PRIMARY KEY (TASKS_ID),
    CONSTRAINT CK__TASKS__ACTUAL_TI__5FB337D6 CHECK (ACTUAL_TIME_TASK_TOOK > 0),
    CONSTRAINT CK__TASKS__EST_HOURS__60A75C0F CHECK (EST_HOURS_IT_WILL_TAKE > 0),
    CONSTRAINT CK__TASKS__HOURLY_RA__619B8048 CHECK (HOURLY_RATE_FOR_TASK > 0)
);
GO

-- 18. USERS_ROLES
CREATE TABLE dbo.USERS_ROLES (
    USERS_ROLES_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    SYS_USER_ID numeric(18,0) NOT NULL,
    ROLE_CODE numeric(18,0) NOT NULL,
    ASSIGNMENT_DATE nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    REVOKE_DATE nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IS_ACTIVE bit NULL,
    CONSTRAINT PK__USERS_RO__DEA33A14CA6A7459 PRIMARY KEY (USERS_ROLES_ID),
    CONSTRAINT UQ_USERS_ROLES_USER_ROLE UNIQUE (SYS_USER_ID, ROLE_CODE)
);
GO

-- 19. USER_LOGIN_LOG
CREATE TABLE dbo.USER_LOGIN_LOG (
    USER_LOGIN_LOG_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    SYS_USER_ID numeric(18,0) NOT NULL,
    LOGIN_DATE nvarchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    CONSTRAINT PK__USER_LOG__437C1838A9454AE3 PRIMARY KEY (USER_LOGIN_LOG_ID)
);
GO

-- 20. WORK_HOUR_REPORT_LOG
CREATE TABLE dbo.WORK_HOUR_REPORT_LOG (
    WORK_HOUR_REPORT_LOG_ID numeric(18,0) IDENTITY(1,1) NOT NULL,
    SYS_USER_ID numeric(18,0) NOT NULL,
    COMPLETED_TASK_ID numeric(18,0) NULL,
    CONSTRAINT PK__WORK_HOU__A4E7734807B0CE13 PRIMARY KEY (WORK_HOUR_REPORT_LOG_ID)
);
GO

-- =====================================================================
-- FUNCTION CREATION
-- =====================================================================

-- GET_USER_ID_BY_SESSION
CREATE FUNCTION dbo.GET_USER_ID_BY_SESSION (@LOGIN_SESSION NVARCHAR(512))
RETURNS NUMERIC
AS
BEGIN
    DECLARE @RESULT NUMERIC = (SELECT TOP 1 SYS_USER_ID FROM dbo.SYS_USERS WHERE LOGIN_SESSION = @LOGIN_SESSION)
    RETURN @RESULT
END
GO

-- LOGIN_LOG_SELECT
CREATE FUNCTION dbo.LOGIN_LOG_SELECT (@TOKEN NVARCHAR(512))
RETURNS TABLE
AS
RETURN
(
    SELECT
        USER_LOGIN_LOG_ID,
        USERNAME,
        LOGIN_DATE
    FROM dbo.USER_LOGIN_LOG ULL
    INNER JOIN dbo.SYS_USERS SU ON ULL.SYS_USER_ID = SU.SYS_USER_ID
    WHERE SU.LOGIN_SESSION = @TOKEN
)
GO

-- ROLES_LOG_SELECT
CREATE FUNCTION dbo.ROLES_LOG_SELECT (@TOKEN NVARCHAR(512))
RETURNS TABLE
AS
RETURN
(
    SELECT
        UR.USERS_ROLES_ID,
        LR.ROLES_TITLE,
        UR.ASSIGNMENT_DATE
    FROM dbo.USERS_ROLES UR
    INNER JOIN dbo.SYS_USERS SU ON UR.SYS_USER_ID = SU.SYS_USER_ID
    INNER JOIN dbo.LT_ROLES LR ON UR.ROLE_CODE = LR.ROLE_CODE
    WHERE SU.LOGIN_SESSION = @TOKEN AND UR.IS_ACTIVE = 1
)
GO

-- =====================================================================
-- STORED PROCEDURE CREATION
-- =====================================================================

-- 1. ACTIVITY_LOG_MANAGER (called by several others)
CREATE PROCEDURE dbo.ACTIVITY_LOG_MANAGER
    @READ_ONLY BIT = 1,
    @LOGGIN_SESSION NVARCHAR(512) = NULL,
    @ACTIVITY_REMARK NVARCHAR(300) = NULL
AS
BEGIN
    DECLARE @SYS_USER_ID NUMERIC = (SELECT TOP 1 SYS_USER_ID FROM dbo.SYS_USERS WHERE LOGIN_SESSION = @LOGGIN_SESSION)

    IF @READ_ONLY = 0
    BEGIN
        INSERT INTO dbo.ACTIVITY_LOG (SYS_USER_ID, ACTIVITY_REMARKS, DATE_TIME)
        VALUES (@SYS_USER_ID, @ACTIVITY_REMARK, CONVERT(NVARCHAR(19), GETDATE(), 120))
        SELECT 1 AS STATUS
    END
    ELSE
    BEGIN
        SELECT ACTIVITY_LOG_ID, AL.SYS_USER_ID, USERNAME, AL.ACTIVITY_REMARKS, DATE_TIME
        FROM dbo.ACTIVITY_LOG AL
        INNER JOIN dbo.SYS_USERS SU ON AL.SYS_USER_ID = SU.SYS_USER_ID
    END
END
GO

-- 2. CHANGE_PASSWORD
CREATE PROCEDURE dbo.CHANGE_PASSWORD
    @NEW_PASSWORD NVARCHAR(50),
    @OLD_PASSWORD NVARCHAR(50),
    @LOGIN_SESSION NVARCHAR(512)
AS
BEGIN
    IF EXISTS(SELECT 1 FROM dbo.SYS_USERS WHERE LOGIN_SESSION = @LOGIN_SESSION
              AND USER_PASSWORD = HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @OLD_PASSWORD, N'4THEYS123#AYIMJO31SEPHSEED')))
    BEGIN
        UPDATE dbo.SYS_USERS
        SET USER_PASSWORD = HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @NEW_PASSWORD, N'4THEYS123#AYIMJO31SEPHSEED'))
        WHERE LOGIN_SESSION = @LOGIN_SESSION
        SELECT 1 AS STATUS
        EXEC dbo.ACTIVITY_LOG_MANAGER 0, @LOGIN_SESSION, N'USER SUCCESSFULLY CHANGED PASSWORD'
    END
    ELSE
    BEGIN
        SELECT 0 AS STATUS
        EXEC dbo.ACTIVITY_LOG_MANAGER 0, @LOGIN_SESSION, N'USER TRIED AND FAILED TO CHANGE PASSWORD'
    END
END
GO

-- 3. CHANGE_USER_CRED_BY_ADMIN
CREATE PROCEDURE dbo.CHANGE_USER_CRED_BY_ADMIN
    @SYS_USER_ID NUMERIC,
    @CHANGE_PASSWORD BIT,
    @CHANGED_DATA NVARCHAR(100)
AS
BEGIN
    IF @CHANGE_PASSWORD = 1
    BEGIN
        UPDATE dbo.SYS_USERS
        SET USER_PASSWORD = HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @CHANGED_DATA, N'4THEYS123#AYIMJO31SEPHSEED'))
        WHERE SYS_USER_ID = @SYS_USER_ID
    END
    ELSE
    BEGIN
        UPDATE dbo.SYS_USERS
        SET USERNAME = @CHANGED_DATA
        WHERE SYS_USER_ID = @SYS_USER_ID
    END
    SELECT 1 AS STATUS
END
GO

-- 4. CHANGE_USERNAME
CREATE PROCEDURE dbo.CHANGE_USERNAME
    @NEW_USERNAME NVARCHAR(50),
    @LOGIN_SESSION NVARCHAR(512)
AS
BEGIN
    UPDATE dbo.SYS_USERS SET USERNAME = @NEW_USERNAME WHERE LOGIN_SESSION = @LOGIN_SESSION
    EXEC dbo.ACTIVITY_LOG_MANAGER 0, @LOGIN_SESSION, N'USER SUCCESSFULLY CHANGED THEIR USERNAME'
    SELECT 1 AS STATUS
END
GO

-- 5. CREATE_UPDATE_DELETE_DRIVER
CREATE PROCEDURE dbo.CREATE_UPDATE_DELETE_DRIVER
    @ACTION                NVARCHAR(50),
    @DRIVER_ID             NUMERIC      = NULL,
    @DRIVER_NAME           NVARCHAR(50) = NULL,
    @DRIVER_LAST_NAME      NVARCHAR(50) = NULL,
    @DRIVERS_NATIONAL_CODE NVARCHAR(50) = NULL,
    @DRIVERS_PHONE_NUMBER  NVARCHAR(50) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET @ACTION = UPPER(@ACTION);

    IF @ACTION = N'CREATE_DRIVER'
       AND @DRIVER_NAME IS NOT NULL
       AND @DRIVER_LAST_NAME IS NOT NULL
       AND @DRIVERS_NATIONAL_CODE IS NOT NULL
       AND @DRIVERS_PHONE_NUMBER IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.DRIVERS WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE)
            INSERT INTO dbo.DRIVERS (DRIVER_NAME, DRIVER_LAST_NAME, DRIVERS_NATIONAL_CODE, DRIVERS_PHONE_NUMBER)
            VALUES (@DRIVER_NAME, @DRIVER_LAST_NAME, @DRIVERS_NATIONAL_CODE, @DRIVERS_PHONE_NUMBER);
        ELSE
            UPDATE dbo.DRIVERS
            SET IS_DELETED = 0,
                DRIVER_NAME = @DRIVER_NAME,
                DRIVER_LAST_NAME = @DRIVER_LAST_NAME,
                DRIVERS_PHONE_NUMBER = @DRIVERS_PHONE_NUMBER
            WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE;
    END

    IF @ACTION = N'UPDATE_DRIVER' AND @DRIVER_ID IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM dbo.DRIVERS WHERE DRIVER_ID = @DRIVER_ID)
            UPDATE dbo.DRIVERS
            SET DRIVER_NAME           = ISNULL(@DRIVER_NAME, DRIVER_NAME),
                DRIVER_LAST_NAME      = ISNULL(@DRIVER_LAST_NAME, DRIVER_LAST_NAME),
                DRIVERS_NATIONAL_CODE = ISNULL(@DRIVERS_NATIONAL_CODE, DRIVERS_NATIONAL_CODE),
                DRIVERS_PHONE_NUMBER  = ISNULL(@DRIVERS_PHONE_NUMBER, DRIVERS_PHONE_NUMBER)
            WHERE DRIVER_ID = @DRIVER_ID;
    END

    IF @ACTION = N'DELETE_DRIVER' AND @DRIVER_ID IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM dbo.DRIVERS WHERE DRIVER_ID = @DRIVER_ID)
            UPDATE dbo.DRIVERS SET IS_DELETED = 1 WHERE DRIVER_ID = @DRIVER_ID;
    END
    SELECT 1
END
GO

-- 6. CREATE_UPDATE_DELETE_INVENTORY_LOCATION
CREATE PROCEDURE dbo.CREATE_UPDATE_DELETE_INVENTORY_LOCATION
    @ACTION                        NVARCHAR(50),
    @INVENTORY_LOCATION_ID         NUMERIC      = NULL,
    @INVENTORY_LOCATION_NAME       NVARCHAR(50) = NULL,
    @INVENTORY_LOCATION_ADDRESS    NVARCHAR(300) = NULL,
    @INVENTORY_LOCATION_LAT        DECIMAL(9, 6) = NULL,
    @INVENTORY_LOCATION_LONG       DECIMAL(9, 6) = NULL,
    @LT_INVENTORY_LOCATION_TYPE_ID NUMERIC      = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET @ACTION = UPPER(@ACTION);

    IF @ACTION = N'CREATE_INVENTORY_LOCATION'
       AND @INVENTORY_LOCATION_NAME IS NOT NULL
       AND @INVENTORY_LOCATION_ADDRESS IS NOT NULL
       AND @INVENTORY_LOCATION_LAT IS NOT NULL
       AND @INVENTORY_LOCATION_LONG IS NOT NULL
       AND @LT_INVENTORY_LOCATION_TYPE_ID IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.INVENTORY_LOCATION
                       WHERE INVENTORY_LOCATION_NAME = @INVENTORY_LOCATION_NAME
                         AND INVENTORY_LOCATION_ADDRESS = @INVENTORY_LOCATION_ADDRESS
                         AND INVENTORY_LOCATION_LAT = @INVENTORY_LOCATION_LAT
                         AND INVENTORY_LOCATION_LONG = @INVENTORY_LOCATION_LONG)
            INSERT INTO dbo.INVENTORY_LOCATION
                (INVENTORY_LOCATION_NAME, INVENTORY_LOCATION_ADDRESS,
                 INVENTORY_LOCATION_LAT, INVENTORY_LOCATION_LONG,
                 LT_INVENTORY_LOCATION_TYPE_ID)
            VALUES
                (@INVENTORY_LOCATION_NAME, @INVENTORY_LOCATION_ADDRESS,
                 @INVENTORY_LOCATION_LAT, @INVENTORY_LOCATION_LONG,
                 @LT_INVENTORY_LOCATION_TYPE_ID);
        ELSE
            UPDATE dbo.INVENTORY_LOCATION
            SET IS_DELETED = 0,
                INVENTORY_LOCATION_NAME = @INVENTORY_LOCATION_NAME,
                INVENTORY_LOCATION_ADDRESS = @INVENTORY_LOCATION_ADDRESS,
                INVENTORY_LOCATION_LAT = @INVENTORY_LOCATION_LAT,
                INVENTORY_LOCATION_LONG = @INVENTORY_LOCATION_LONG,
                LT_INVENTORY_LOCATION_TYPE_ID = @LT_INVENTORY_LOCATION_TYPE_ID
            WHERE INVENTORY_LOCATION_NAME = @INVENTORY_LOCATION_NAME
              AND INVENTORY_LOCATION_ADDRESS = @INVENTORY_LOCATION_ADDRESS
              AND INVENTORY_LOCATION_LAT = @INVENTORY_LOCATION_LAT
              AND INVENTORY_LOCATION_LONG = @INVENTORY_LOCATION_LONG;
    END

    IF @ACTION = N'UPDATE_INVENTORY_LOCATION' AND @INVENTORY_LOCATION_ID IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM dbo.INVENTORY_LOCATION WHERE INVENTORY_LOCATION_ID = @INVENTORY_LOCATION_ID)
            UPDATE dbo.INVENTORY_LOCATION
            SET INVENTORY_LOCATION_NAME       = ISNULL(@INVENTORY_LOCATION_NAME, INVENTORY_LOCATION_NAME),
                INVENTORY_LOCATION_ADDRESS    = ISNULL(@INVENTORY_LOCATION_ADDRESS, INVENTORY_LOCATION_ADDRESS),
                INVENTORY_LOCATION_LAT        = ISNULL(@INVENTORY_LOCATION_LAT, INVENTORY_LOCATION_LAT),
                INVENTORY_LOCATION_LONG       = ISNULL(@INVENTORY_LOCATION_LONG, INVENTORY_LOCATION_LONG),
                LT_INVENTORY_LOCATION_TYPE_ID = ISNULL(@LT_INVENTORY_LOCATION_TYPE_ID, LT_INVENTORY_LOCATION_TYPE_ID)
            WHERE INVENTORY_LOCATION_ID = @INVENTORY_LOCATION_ID;
    END

    IF @ACTION = N'DELETE_INVENTORY_LOCATION' AND @INVENTORY_LOCATION_ID IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM dbo.INVENTORY_LOCATION WHERE INVENTORY_LOCATION_ID = @INVENTORY_LOCATION_ID)
            UPDATE dbo.INVENTORY_LOCATION SET IS_DELETED = 1 WHERE INVENTORY_LOCATION_ID = @INVENTORY_LOCATION_ID;
    END
    SELECT 1
END
GO

-- 7. CREATE_UPDATE_DELETE_ROLES
CREATE PROCEDURE dbo.CREATE_UPDATE_DELETE_ROLES
    @ACTION_NAME NVARCHAR(20),
    @ROLE_CODE NUMERIC = 0,
    @ROLE_NAME NVARCHAR(50) = NULL,
    @SYS_OBJECT_NAME NVARCHAR(50) = NULL,
    @CAN_READ BIT = 0,
    @CAN_WRITE BIT = 0
AS
BEGIN
    DECLARE @OBJECT_CODE NUMERIC = (SELECT TOP 1 SYS_OBJECT_CODE FROM dbo.SYS_OBJECTS WHERE SYS_OBJECT_NAME = @SYS_OBJECT_NAME)
    IF LOWER(@ACTION_NAME) = LOWER(N'DELETE_ROLE') AND NOT @ROLE_CODE = 0
    BEGIN
        DELETE FROM dbo.SYS_CALL_ACCESS WHERE ROLE_CODE = @ROLE_CODE
        DELETE FROM dbo.LT_ROLES WHERE ROLE_CODE = @ROLE_CODE
    END
    ELSE IF LOWER(@ACTION_NAME) = LOWER(N'CREATE_ROLE') AND @ROLE_NAME IS NOT NULL
            AND NOT EXISTS(SELECT 1 FROM dbo.LT_ROLES WHERE ROLE_CODE = @ROLE_CODE)
    BEGIN
        INSERT INTO dbo.LT_ROLES (ROLE_CODE, ROLES_TITLE) VALUES (@ROLE_CODE, @ROLE_NAME)
    END
    ELSE IF LOWER(@ACTION_NAME) = LOWER(N'UPDATE_ROLE') AND NOT @ROLE_CODE = 0
    BEGIN
        UPDATE dbo.LT_ROLES SET ROLES_TITLE = @ROLE_NAME WHERE ROLE_CODE = @ROLE_CODE
    END
    ELSE IF LOWER(@ACTION_NAME) = LOWER(N'ADD_PERMISSION') AND NOT @ROLE_CODE = 0 AND @SYS_OBJECT_NAME IS NOT NULL
            AND EXISTS(SELECT TOP 1 1 FROM dbo.SYS_OBJECTS WHERE SYS_OBJECT_NAME = @SYS_OBJECT_NAME)
            AND EXISTS(SELECT TOP 1 1 FROM dbo.LT_ROLES WHERE ROLE_CODE = @ROLE_CODE)
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM dbo.SYS_CALL_ACCESS WHERE SYS_OBJECT_CODE = @OBJECT_CODE AND ROLE_CODE = @ROLE_CODE)
            INSERT INTO dbo.SYS_CALL_ACCESS (ROLE_CODE, SYS_OBJECT_CODE, CAN_READ, CAN_WRITE)
            VALUES (@ROLE_CODE, @OBJECT_CODE, @CAN_READ, @CAN_WRITE)
        ELSE
            UPDATE dbo.SYS_CALL_ACCESS
            SET CAN_READ = @CAN_READ,
                CAN_WRITE = @CAN_WRITE
            WHERE SYS_OBJECT_CODE = @OBJECT_CODE AND ROLE_CODE = @ROLE_CODE
    END
    ELSE IF LOWER(@ACTION_NAME) = LOWER(N'DELETE_PERMISSION') AND NOT @ROLE_CODE = 0 AND @SYS_OBJECT_NAME IS NOT NULL
    BEGIN
        DELETE FROM dbo.SYS_CALL_ACCESS WHERE SYS_OBJECT_CODE = @OBJECT_CODE AND ROLE_CODE = @ROLE_CODE
    END

    SELECT 1 AS STATUS
END
GO

-- 8. CREATE_UPDATE_DELETE_VEHICLE
CREATE PROCEDURE dbo.CREATE_UPDATE_DELETE_VEHICLE
    @ACTION NVARCHAR(50),
    @VEHICLE_ID NUMERIC = NULL,
    @VEHICLE_NAME NVARCHAR(50) = NULL,
    @VEHICLE_LICENCE_PLATE NVARCHAR(50) = NULL
AS
BEGIN
    SET @ACTION = UPPER(@ACTION)

    IF @ACTION = N'CREATE_VEHICLE' AND @VEHICLE_NAME IS NOT NULL AND @VEHICLE_LICENCE_PLATE IS NOT NULL
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM dbo.VEHICLE WHERE VEHICLE_NAME = @VEHICLE_NAME AND VEHICLE_LICENCE_PLATE = @VEHICLE_LICENCE_PLATE)
            INSERT INTO dbo.VEHICLE (VEHICLE_NAME, VEHICLE_LICENCE_PLATE)
            VALUES (@VEHICLE_NAME, @VEHICLE_LICENCE_PLATE)
        ELSE
            UPDATE dbo.VEHICLE SET IS_DELETED = 0 WHERE VEHICLE_NAME = @VEHICLE_NAME AND VEHICLE_LICENCE_PLATE = @VEHICLE_LICENCE_PLATE
    END

    IF @ACTION = N'UPDATE_VEHICLE' AND @VEHICLE_ID IS NOT NULL
    BEGIN
        IF EXISTS(SELECT 1 FROM dbo.VEHICLE WHERE VEHICLE_ID = @VEHICLE_ID)
            UPDATE dbo.VEHICLE
            SET VEHICLE_NAME = ISNULL(@VEHICLE_NAME, VEHICLE_NAME),
                VEHICLE_LICENCE_PLATE = ISNULL(@VEHICLE_LICENCE_PLATE, VEHICLE_LICENCE_PLATE)
            WHERE VEHICLE_ID = @VEHICLE_ID
    END

    IF @ACTION = N'DELETE_VEHICLE' AND @VEHICLE_ID IS NOT NULL
    BEGIN
        IF EXISTS(SELECT 1 FROM dbo.VEHICLE WHERE VEHICLE_ID = @VEHICLE_ID)
            UPDATE dbo.VEHICLE SET IS_DELETED = 1 WHERE VEHICLE_ID = @VEHICLE_ID
    END

    SELECT 1;
END
GO

-- 9. HANDLE_INVENTORY_REQUEST
CREATE PROCEDURE dbo.HANDLE_INVENTORY_REQUEST
    @ACTION                     NVARCHAR(50),
    @INVENTORY_STOCK_REQUEST_ID NUMERIC = NULL,
    @INVENTORY_ID               NUMERIC = NULL,
    @PRODUCTS_ID                NUMERIC = NULL,
    @PRODUCTS_COUNT             NUMERIC = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET @ACTION = UPPER(@ACTION);

    IF @ACTION = N'SET_REQUEST'
    BEGIN
        IF @INVENTORY_ID IS NULL
            THROW 50001, 'INVENTORY_ID cannot be NULL for SET_REQUEST.', 1;
        IF @PRODUCTS_ID IS NULL
            THROW 50001, 'PRODUCTS_ID cannot be NULL for SET_REQUEST.', 1;
        IF @PRODUCTS_COUNT IS NULL
            THROW 50001, 'PRODUCTS_COUNT cannot be NULL for SET_REQUEST.', 1;

        INSERT INTO dbo.INVENTORY_STOCK_REQUEST
            (INVENTORY_ID, PRODUCTS_ID, IS_DELETED, IS_ACCEPTED_BY_FLEET, PRODUCTS_COUNT)
        VALUES
            (@INVENTORY_ID, @PRODUCTS_ID, 0, 0, @PRODUCTS_COUNT);
    END

    IF @ACTION = N'ACCEPT_REQUEST'
    BEGIN
        IF @INVENTORY_STOCK_REQUEST_ID IS NULL
            THROW 50002, 'INVENTORY_STOCK_REQUEST_ID cannot be NULL for ACCEPT_REQUEST.', 1;
        IF @INVENTORY_ID IS NULL
            THROW 50002, 'INVENTORY_ID cannot be NULL for ACCEPT_REQUEST.', 1;
        IF @PRODUCTS_ID IS NULL
            THROW 50002, 'PRODUCTS_ID cannot be NULL for ACCEPT_REQUEST.', 1;

        IF NOT EXISTS (
            SELECT 1 FROM dbo.INVENTORY_STOCK_REQUEST
            WHERE INVENTORY_STOCK_REQUEST_ID = @INVENTORY_STOCK_REQUEST_ID AND IS_DELETED = 0
        )
            THROW 50003, 'Request not found or has been deleted.', 1;

        IF EXISTS (
            SELECT 1 FROM dbo.INVENTORY_STOCK_REQUEST
            WHERE INVENTORY_STOCK_REQUEST_ID = @INVENTORY_STOCK_REQUEST_ID AND INVENTORY_ID = @INVENTORY_ID
        )
            THROW 50004, 'Source and destination inventory cannot be the same.', 1;

        UPDATE dbo.INVENTORY_STOCK_REQUEST
        SET FROM_INVENTORY_ID = @INVENTORY_ID,
            PRODUCTS_ID = @PRODUCTS_ID,
            ACCEPT_BY_INVENTORY_ID = @INVENTORY_ID
        WHERE INVENTORY_STOCK_REQUEST_ID = @INVENTORY_STOCK_REQUEST_ID;
    END
    SELECT 1 AS STATUS
END
GO

-- 10. IS_ALLOWED
CREATE PROCEDURE dbo.IS_ALLOWED
    @LOGIN_SESSION NVARCHAR(512),
    @SYS_OBJECT_CODE NUMERIC
AS
BEGIN
    IF EXISTS (SELECT 1 FROM dbo.SYS_CALL_ACCESS
               WHERE SYS_OBJECT_CODE = @SYS_OBJECT_CODE
                 AND ROLE_CODE IN (SELECT ROLE_CODE FROM dbo.USERS_ROLES
                                   WHERE ISNULL(IS_ACTIVE, 1) = 1
                                     AND SYS_USER_ID = (SELECT SYS_USER_ID FROM dbo.SYS_USERS WHERE LOGIN_SESSION = @LOGIN_SESSION)))
    BEGIN
        SELECT 1 AS RESULT
    END
    ELSE
    BEGIN
        SELECT 0 AS RESULT
    END
END
GO

-- 11. IS_ALLOWED_READ
CREATE PROCEDURE dbo.IS_ALLOWED_READ
    @LOGIN_SESSION NVARCHAR(512),
    @SYS_OBJECT_CODE NUMERIC
AS
BEGIN
    IF EXISTS (SELECT 1 FROM dbo.SYS_CALL_ACCESS
               WHERE CAN_READ = 1
                 AND SYS_OBJECT_CODE = @SYS_OBJECT_CODE
                 AND ROLE_CODE IN (SELECT ROLE_CODE FROM dbo.USERS_ROLES
                                   WHERE ISNULL(IS_ACTIVE, 1) = 1
                                     AND SYS_USER_ID = (SELECT SYS_USER_ID FROM dbo.SYS_USERS WHERE LOGIN_SESSION = @LOGIN_SESSION)))
    BEGIN
        SELECT 1 AS RESULT
    END
    ELSE
    BEGIN
        SELECT 0 AS RESULT
    END
END
GO

-- 12. IS_AUTHENTICATED
CREATE PROCEDURE dbo.IS_AUTHENTICATED
    @TOKEN NVARCHAR(MAX)
AS
BEGIN
    SELECT TOP 1
        CASE WHEN EXISTS(SELECT 1 FROM dbo.SYS_USERS WHERE LOGIN_SESSION = @TOKEN)
             THEN 1
             ELSE 0
        END AS RESULT
    FROM dbo.SYS_USERS
END
GO

-- 13. LOGIN_VALID
CREATE PROCEDURE dbo.LOGIN_VALID
    @USERNAME NVARCHAR(50),
    @PASSWORD NVARCHAR(50)
AS
BEGIN
    DECLARE @USER_ID NUMERIC = (SELECT SYS_USER_ID FROM dbo.SYS_USERS
                                WHERE LOWER(USERNAME) = LOWER(@USERNAME)
                                  AND USER_PASSWORD = HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @PASSWORD, N'4THEYS123#AYIMJO31SEPHSEED')));
    IF @USER_ID IS NOT NULL
    BEGIN
        DECLARE @TOKENVARBINARY VARBINARY(512)
        SET @TOKENVARBINARY = HASHBYTES('SHA2_512', CONCAT(N'I%@MBAR#4BI$GI$RL', @USERNAME, N'4THEYS123#AYIMJO31SEPHSEED', CAST(GETUTCDATE() AS NVARCHAR)))
        DECLARE @TOKEN NVARCHAR(512) = CONVERT(NVARCHAR(512), @TOKENVARBINARY, 2);

        UPDATE dbo.SYS_USERS
        SET LOGIN_SESSION = @TOKEN
        WHERE SYS_USER_ID = @USER_ID

        INSERT INTO dbo.USER_LOGIN_LOG (SYS_USER_ID, LOGIN_DATE)
        VALUES (@USER_ID, CONVERT(NVARCHAR(19), GETDATE(), 120))

        SELECT 1 AS RESULT, @TOKEN AS TOKEN
    END
    ELSE
        SELECT 0 AS RESULT, N'' AS TOKEN
END
GO

-- 14. MANAGE_DRIVERS_AND_TEAMS
CREATE PROCEDURE dbo.MANAGE_DRIVERS_AND_TEAMS
    @ACTION NVARCHAR(50),
    @DRIVER_NAME NVARCHAR(50) = NULL,
    @DRIVER_LAST_NAME NVARCHAR(50) = NULL,
    @DRIVERS_NATIONAL_CODE NVARCHAR(50) = NULL,
    @NEW_DRIVER_NAME NVARCHAR(50) = NULL,
    @NEW_DRIVER_LAST_NAME NVARCHAR(50) = NULL,
    @NEW_DRIVERS_NATIONAL_CODE NVARCHAR(50) = NULL,
    @DRIVERS_PHONE_NUMBER NVARCHAR(50) = NULL,
    @NEW_DRIVERS_PHONE_NUMBER NVARCHAR(50) = NULL,
    @FLEET_TEAM_NAME NVARCHAR(50) = NULL,
    @NEW_FLEET_TEAM_NAME NVARCHAR(50) = NULL,
    @DESCRIPTION NVARCHAR(100) = NULL,
    @NEW_DESCRIPTION NVARCHAR(100) = NULL
AS
BEGIN
    DECLARE @FLEET_ID NUMERIC = (SELECT TOP 1 FLEET_TEAM_ID FROM dbo.FLEET_TEAMS WHERE LOWER(FLEET_TEAM_NAME) LIKE LOWER(@FLEET_TEAM_NAME))

    IF LOWER(@ACTION) = LOWER(N'ADD_DRIVER')
       AND @DRIVERS_NATIONAL_CODE IS NOT NULL
       AND @DRIVER_NAME IS NOT NULL
       AND @DRIVER_LAST_NAME IS NOT NULL
       AND @DRIVERS_PHONE_NUMBER IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.DRIVERS WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE)
            INSERT INTO dbo.DRIVERS (DRIVER_NAME, DRIVER_LAST_NAME, DRIVERS_NATIONAL_CODE, DRIVERS_PHONE_NUMBER, IS_DELETED, FLEET_TEAM_ID)
            VALUES (@DRIVER_NAME, @DRIVER_LAST_NAME, @DRIVERS_NATIONAL_CODE, @DRIVERS_PHONE_NUMBER, 0, @FLEET_ID);
        ELSE
            UPDATE dbo.DRIVERS SET IS_DELETED = 0 WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE;
    END

    IF LOWER(@ACTION) = LOWER(N'MODIFY_DRIVER') AND @DRIVERS_NATIONAL_CODE IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM dbo.DRIVERS WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE)
            UPDATE dbo.DRIVERS
            SET DRIVER_NAME = ISNULL(@NEW_DRIVER_NAME, DRIVER_NAME),
                DRIVER_LAST_NAME = ISNULL(@NEW_DRIVER_LAST_NAME, DRIVER_LAST_NAME),
                DRIVERS_NATIONAL_CODE = ISNULL(@NEW_DRIVERS_NATIONAL_CODE, DRIVERS_NATIONAL_CODE),
                DRIVERS_PHONE_NUMBER = ISNULL(@NEW_DRIVERS_PHONE_NUMBER, DRIVERS_PHONE_NUMBER),
                FLEET_TEAM_ID = ISNULL(@FLEET_ID, FLEET_TEAM_ID)
            WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE;
    END

    IF LOWER(@ACTION) = LOWER(N'DELETE_DRIVER') AND @DRIVERS_NATIONAL_CODE IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM dbo.DRIVERS WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE)
            UPDATE dbo.DRIVERS SET IS_DELETED = 1 WHERE DRIVERS_NATIONAL_CODE = @DRIVERS_NATIONAL_CODE;
    END

    IF LOWER(@ACTION) = LOWER(N'ADD_FLEET_TEAM') AND @FLEET_TEAM_NAME IS NOT NULL AND @DESCRIPTION IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.FLEET_TEAMS WHERE FLEET_TEAM_NAME = @FLEET_TEAM_NAME)
            INSERT INTO dbo.FLEET_TEAMS (FLEET_TEAM_NAME, DESCRIPTION, IS_DELETED)
            VALUES (@FLEET_TEAM_NAME, @DESCRIPTION, 0);
        ELSE
            UPDATE dbo.FLEET_TEAMS SET IS_DELETED = 0 WHERE FLEET_TEAM_NAME = @FLEET_TEAM_NAME;
    END

    IF LOWER(@ACTION) = LOWER(N'MODIFY_FLEET_TEAM') AND @FLEET_TEAM_NAME IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM dbo.FLEET_TEAMS WHERE FLEET_TEAM_NAME = @FLEET_TEAM_NAME)
            UPDATE dbo.FLEET_TEAMS
            SET FLEET_TEAM_NAME = ISNULL(@NEW_FLEET_TEAM_NAME, FLEET_TEAM_NAME),
                DESCRIPTION = ISNULL(@NEW_DESCRIPTION, DESCRIPTION)
            WHERE FLEET_TEAM_NAME = @FLEET_TEAM_NAME;
    END

    IF LOWER(@ACTION) = LOWER(N'DELETE_FLEET_TEAM') AND @FLEET_TEAM_NAME IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM dbo.FLEET_TEAMS WHERE FLEET_TEAM_NAME = @FLEET_TEAM_NAME)
            UPDATE dbo.FLEET_TEAMS SET IS_DELETED = 1 WHERE FLEET_TEAM_NAME = @FLEET_TEAM_NAME;
    END

    SELECT 1;
END
GO

-- 15. MANAGE_INVENTORY_INFSTRUCTURE
CREATE PROCEDURE dbo.MANAGE_INVENTORY_INFSTRUCTURE
    @ACTION NVARCHAR(50),
    @INVENTORY_LOCATION_TITLE NVARCHAR(50) = NULL,
    @NEW_INVENTORY_LOCATION_TITLE NVARCHAR(50) = NULL,
    @PRODUCTS_NAME NVARCHAR(50) = NULL,
    @NEW_PRODUCTS_NAME NVARCHAR(50) = NULL,
    @PRODUCTS_CATEGORY_ID NUMERIC = NULL,
    @PRODUCTS_CATEGORY_NAME NVARCHAR(50) = NULL,
    @NEW_PRODUCTS_CATEGORY_NAME NVARCHAR(50) = NULL
AS
BEGIN
    IF LOWER(@ACTION) = LOWER(N'ADD_INVENTORY_TYPE') AND @INVENTORY_LOCATION_TITLE IS NOT NULL
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM dbo.LT_INVENTORY_LOCATION_TYPE WHERE INVENTORY_LOCATION_TYPE_TITLE LIKE @INVENTORY_LOCATION_TITLE)
            INSERT INTO dbo.LT_INVENTORY_LOCATION_TYPE (INVENTORY_LOCATION_TYPE_TITLE) VALUES (@INVENTORY_LOCATION_TITLE)
        ELSE
            UPDATE dbo.LT_INVENTORY_LOCATION_TYPE SET IS_DELETED = 0 WHERE INVENTORY_LOCATION_TYPE_TITLE LIKE @INVENTORY_LOCATION_TITLE
    END

    IF LOWER(@ACTION) = LOWER(N'MODIFY_INVENTORY_TYPE') AND @INVENTORY_LOCATION_TITLE IS NOT NULL
    BEGIN
        IF EXISTS(SELECT 1 FROM dbo.LT_INVENTORY_LOCATION_TYPE WHERE INVENTORY_LOCATION_TYPE_TITLE LIKE @INVENTORY_LOCATION_TITLE)
            UPDATE dbo.LT_INVENTORY_LOCATION_TYPE SET INVENTORY_LOCATION_TYPE_TITLE = @NEW_INVENTORY_LOCATION_TITLE WHERE INVENTORY_LOCATION_TYPE_TITLE LIKE @INVENTORY_LOCATION_TITLE
    END

    IF LOWER(@ACTION) = LOWER(N'DELETE_INVENTORY_TYPE') AND @INVENTORY_LOCATION_TITLE IS NOT NULL
    BEGIN
        IF EXISTS(SELECT 1 FROM dbo.LT_INVENTORY_LOCATION_TYPE WHERE INVENTORY_LOCATION_TYPE_TITLE LIKE @INVENTORY_LOCATION_TITLE)
            UPDATE dbo.LT_INVENTORY_LOCATION_TYPE SET IS_DELETED = 1 WHERE INVENTORY_LOCATION_TYPE_TITLE LIKE @INVENTORY_LOCATION_TITLE
    END

    IF LOWER(@ACTION) = LOWER(N'ADD_PRODUCTS_CATEGORY') AND @PRODUCTS_CATEGORY_NAME IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM dbo.PRODUCTS_CATEGORY WHERE PRODUCTS_CATEGORY_NAME = @PRODUCTS_CATEGORY_NAME)
            INSERT INTO dbo.PRODUCTS_CATEGORY (PRODUCTS_CATEGORY_NAME) VALUES (@PRODUCTS_CATEGORY_NAME)
        ELSE
            UPDATE dbo.PRODUCTS_CATEGORY SET IS_DELETED = 0 WHERE PRODUCTS_CATEGORY_NAME = @PRODUCTS_CATEGORY_NAME
    END

    IF LOWER(@ACTION) = LOWER(N'MODIFY_PRODUCTS_CATEGORY') AND @PRODUCTS_CATEGORY_NAME IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM dbo.PRODUCTS_CATEGORY WHERE PRODUCTS_CATEGORY_NAME = @PRODUCTS_CATEGORY_NAME)
            UPDATE dbo.PRODUCTS_CATEGORY SET PRODUCTS_CATEGORY_NAME = @NEW_PRODUCTS_CATEGORY_NAME WHERE PRODUCTS_CATEGORY_NAME = @PRODUCTS_CATEGORY_NAME
    END

    IF LOWER(@ACTION) = LOWER(N'DELETE_PRODUCTS_CATEGORY') AND @PRODUCTS_CATEGORY_NAME IS NOT NULL
    BEGIN
        IF EXISTS (SELECT 1 FROM dbo.PRODUCTS_CATEGORY WHERE PRODUCTS_CATEGORY_NAME = @PRODUCTS_CATEGORY_NAME)
            UPDATE dbo.PRODUCTS_CATEGORY SET IS_DELETED = 1 WHERE PRODUCTS_CATEGORY_NAME = @PRODUCTS_CATEGORY_NAME
    END

    IF LOWER(@ACTION) = LOWER(N'ADD_PRODUCTS') AND @PRODUCTS_NAME IS NOT NULL AND @PRODUCTS_CATEGORY_ID IS NOT NULL
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM dbo.PRODUCTS WHERE PRODUCTS_NAME = @PRODUCTS_NAME)
            INSERT INTO dbo.PRODUCTS (PRODUCTS_NAME, PRODUCTS_CATEGORY_ID, IS_DELETED) VALUES (@PRODUCTS_NAME, @PRODUCTS_CATEGORY_ID, 0)
        ELSE
            UPDATE dbo.PRODUCTS SET IS_DELETED = 0 WHERE PRODUCTS_NAME = @PRODUCTS_NAME
    END

    IF LOWER(@ACTION) = LOWER(N'MODIFY_PRODUCTS')
    BEGIN
        IF EXISTS(SELECT 1 FROM dbo.PRODUCTS WHERE PRODUCTS_NAME = @PRODUCTS_NAME)
            UPDATE dbo.PRODUCTS SET PRODUCTS_NAME = ISNULL(@NEW_PRODUCTS_NAME, PRODUCTS_NAME), PRODUCTS_CATEGORY_ID = ISNULL(@PRODUCTS_CATEGORY_ID, PRODUCTS_CATEGORY_ID) WHERE PRODUCTS_NAME = @PRODUCTS_NAME
    END

    IF LOWER(@ACTION) = LOWER(N'DELETE_PRODUCTS') AND @PRODUCTS_NAME IS NOT NULL
    BEGIN
        IF EXISTS(SELECT 1 FROM dbo.PRODUCTS WHERE PRODUCTS_NAME = @PRODUCTS_NAME)
            UPDATE dbo.PRODUCTS SET IS_DELETED = 1 WHERE PRODUCTS_NAME = @PRODUCTS_NAME
    END

    SELECT 1;
END
GO

-- 16. MANAGE_PRODUCTS_MOVEMENT_TRIPS
CREATE PROCEDURE dbo.MANAGE_PRODUCTS_MOVEMENT_TRIPS
    @ACTION NVARCHAR(50) = NULL,
    @PRODUCTS_MOVEMENTS_ID NUMERIC = NULL,
    @DRIVERS_ID NUMERIC = NULL,
    @VEHICLE_ID NUMERIC = NULL,
    @COMES_FROM_LOCATION_ID NUMERIC = NULL,
    @GOES_TO_LOCATION_ID NUMERIC = NULL,
    @EST_ARIVAL NVARCHAR(19) = NULL,
    @DID_ARIVE BIT = NULL,
    @PRODUCTS_MOVEMENTS_LIST_ID NUMERIC = NULL,
    @PRODUCTS_ID NUMERIC = NULL,
    @PRODUCTS_COUNT NUMERIC = NULL
AS
BEGIN
    SET @ACTION = UPPER(@ACTION)

    IF @ACTION = N'DELETE_TRIP'
       AND @PRODUCTS_MOVEMENTS_ID IS NOT NULL
       AND (SELECT TOP(1) START_DATE_HOUR FROM dbo.PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NULL
    BEGIN
        UPDATE dbo.PRODUCTS_MOVEMENTS
        SET IS_DELETED = 1,
            IS_ACTIVE = 0
        WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID

        DELETE FROM dbo.MOVEMENTS_PRODUCTS_LIST WHERE MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID
    END

    IF @ACTION = N'ADD_PRODUCT_TO_TRIP'
       AND @PRODUCTS_MOVEMENTS_ID IS NOT NULL
       AND @PRODUCTS_ID IS NOT NULL
       AND @PRODUCTS_COUNT IS NOT NULL
       AND (SELECT TOP(1) START_DATE_HOUR FROM dbo.PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NULL
    BEGIN
        INSERT INTO dbo.MOVEMENTS_PRODUCTS_LIST (MOVEMENTS_ID, PRODUCTS_ID, PRODUCTS_COUNT)
        VALUES (@PRODUCTS_MOVEMENTS_ID, @PRODUCTS_ID, @PRODUCTS_COUNT)
    END

    IF @ACTION = N'DELETE_PRODUCT_FROM_TRIP' AND @PRODUCTS_MOVEMENTS_LIST_ID IS NOT NULL
       AND (SELECT TOP(1) START_DATE_HOUR FROM dbo.PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NULL
    BEGIN
        DELETE FROM dbo.MOVEMENTS_PRODUCTS_LIST WHERE MOVEMENTS_PRODUCTS_ID = @PRODUCTS_MOVEMENTS_LIST_ID
    END

    IF @ACTION = N'MODIFY_PRODUCT_FROM_TRIP' AND @PRODUCTS_MOVEMENTS_LIST_ID IS NOT NULL
       AND (SELECT TOP(1) START_DATE_HOUR FROM dbo.PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NULL
    BEGIN
        UPDATE dbo.MOVEMENTS_PRODUCTS_LIST
        SET PRODUCTS_ID = ISNULL(@PRODUCTS_ID, PRODUCTS_ID),
            PRODUCTS_COUNT = ISNULL(@PRODUCTS_COUNT, PRODUCTS_COUNT)
        WHERE MOVEMENTS_PRODUCTS_ID = @PRODUCTS_MOVEMENTS_LIST_ID
    END

    IF @ACTION = N'ADD_PRODUCTS_TRIP'
       AND @DRIVERS_ID IS NOT NULL
       AND @VEHICLE_ID IS NOT NULL
       AND @COMES_FROM_LOCATION_ID IS NOT NULL
       AND @GOES_TO_LOCATION_ID IS NOT NULL
       AND @COMES_FROM_LOCATION_ID <> @GOES_TO_LOCATION_ID
    BEGIN
        INSERT INTO dbo.PRODUCTS_MOVEMENTS (DRIVERS_ID, VEHICLE_ID, COMES_FROM_LOCATION_ID, GOES_TO_LOCATION_ID)
        VALUES (@DRIVERS_ID, @VEHICLE_ID, @COMES_FROM_LOCATION_ID, @GOES_TO_LOCATION_ID)
    END

    IF @ACTION = N'MODIFY_TRIP'
       AND @PRODUCTS_MOVEMENTS_ID IS NOT NULL
       AND (SELECT START_DATE_HOUR FROM dbo.PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NULL
    BEGIN
        UPDATE dbo.PRODUCTS_MOVEMENTS
        SET DRIVERS_ID = ISNULL(@DRIVERS_ID, DRIVERS_ID),
            VEHICLE_ID = ISNULL(@VEHICLE_ID, VEHICLE_ID),
            COMES_FROM_LOCATION_ID = ISNULL(@COMES_FROM_LOCATION_ID, COMES_FROM_LOCATION_ID),
            GOES_TO_LOCATION_ID = ISNULL(@GOES_TO_LOCATION_ID, GOES_TO_LOCATION_ID)
        WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID
    END

    IF @ACTION = N'START_TRIP' AND @PRODUCTS_MOVEMENTS_ID IS NOT NULL
       AND (SELECT START_DATE_HOUR FROM dbo.PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NULL
    BEGIN
        UPDATE dbo.PRODUCTS_MOVEMENTS
        SET START_DATE_HOUR = CONVERT(NVARCHAR(19), GETDATE(), 20),
            EST_ARIVAL = ISNULL(@EST_ARIVAL, EST_ARIVAL)
        WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID
    END

    IF @ACTION = N'END_TRIP' AND @PRODUCTS_MOVEMENTS_ID IS NOT NULL
       AND (SELECT END_DATE_HOUR FROM dbo.PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NULL
       AND (SELECT START_DATE_HOUR FROM dbo.PRODUCTS_MOVEMENTS WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID) IS NOT NULL
    BEGIN
        UPDATE dbo.PRODUCTS_MOVEMENTS
        SET END_DATE_HOUR = CONVERT(NVARCHAR(19), GETDATE(), 20),
            DID_ARIVE = ISNULL(@DID_ARIVE, DID_ARIVE),
            IS_ACTIVE = 0
        WHERE PRODUCTS_MOVEMENTS_ID = @PRODUCTS_MOVEMENTS_ID
    END

    SELECT 1
END
GO

-- 17. ROLES_MANAGEMENT
CREATE PROCEDURE dbo.ROLES_MANAGEMENT
    @USERNAME NVARCHAR(50),
    @ROLES_TITLE NVARCHAR(50),
    @REVOKE BIT = 0
AS
BEGIN
    DECLARE @SYS_USER_ID NUMERIC = (SELECT TOP 1 SYS_USER_ID FROM dbo.SYS_USERS WHERE LOWER(USERNAME) LIKE LOWER(@USERNAME))
    DECLARE @ROLE_CODE NUMERIC = (SELECT TOP 1 ROLE_CODE FROM dbo.LT_ROLES WHERE LOWER(ROLES_TITLE) LIKE LOWER(@ROLES_TITLE))
    DECLARE @EXISTS BIT = 0;

    IF EXISTS(SELECT 1 FROM dbo.USERS_ROLES WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE)
        SET @EXISTS = 1

    IF @SYS_USER_ID IS NOT NULL AND @ROLE_CODE IS NOT NULL
    BEGIN
        IF NOT(@REVOKE = 1)
        BEGIN
            IF @EXISTS = 1
                UPDATE dbo.USERS_ROLES SET IS_ACTIVE = 1 WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE
            ELSE
                INSERT INTO dbo.USERS_ROLES (SYS_USER_ID, ROLE_CODE, ASSIGNMENT_DATE, IS_ACTIVE)
                VALUES (@SYS_USER_ID, @ROLE_CODE, CONVERT(NVARCHAR(19), GETDATE(), 120), 1)
        END
        ELSE
        BEGIN
            IF @EXISTS = 1
                UPDATE dbo.USERS_ROLES SET IS_ACTIVE = 0 WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE
        END
    END

    SELECT 1 AS STATUS
END
GO

-- 18. ROLES_MANAGEMENT_ID_BASED
CREATE PROCEDURE dbo.ROLES_MANAGEMENT_ID_BASED
    @REVOKE BIT = 0,
    @SYS_USER_ID NUMERIC,
    @ROLE_CODE NUMERIC
AS
BEGIN
    DECLARE @EXISTS BIT = 0;
    IF EXISTS(SELECT 1 FROM dbo.USERS_ROLES WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE)
        SET @EXISTS = 1

    IF @SYS_USER_ID IS NOT NULL AND @ROLE_CODE IS NOT NULL
    BEGIN
        IF NOT(@REVOKE = 1)
        BEGIN
            IF @EXISTS = 1
                UPDATE dbo.USERS_ROLES SET IS_ACTIVE = 1 WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE
            ELSE
                INSERT INTO dbo.USERS_ROLES (SYS_USER_ID, ROLE_CODE, ASSIGNMENT_DATE, IS_ACTIVE)
                VALUES (@SYS_USER_ID, @ROLE_CODE, CONVERT(NVARCHAR(19), GETDATE(), 120), 1)
        END
        ELSE
        BEGIN
            IF @EXISTS = 1
                UPDATE dbo.USERS_ROLES SET IS_ACTIVE = 0 WHERE SYS_USER_ID = @SYS_USER_ID AND ROLE_CODE = @ROLE_CODE
        END
    END
    SELECT 1 AS STATUS
END
GO

-- 19. SIGNUP_NEWUSER
CREATE PROCEDURE dbo.SIGNUP_NEWUSER
    @USERNAME NVARCHAR(50),
    @PASSWORD NVARCHAR(100)
AS
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo.SYS_USERS WHERE LOWER(USERNAME) LIKE LOWER(@USERNAME))
    BEGIN
        INSERT INTO dbo.SYS_USERS (USERNAME, USER_PASSWORD)
        VALUES (LOWER(@USERNAME), HASHBYTES('SHA2_256', CONCAT(N'I%@MBAR#4BI$GI$RL', @PASSWORD, N'4THEYS123#AYIMJO31SEPHSEED')))
        SELECT 1 AS RESULT
    END
    ELSE
    BEGIN
        SELECT 0 AS RESULT
    END
END
GO

-- 20. TASKS_REPORT
CREATE PROCEDURE dbo.TASKS_REPORT
    @BY_USER_SESSION NVARCHAR(512) = NULL,
    @TASK_ID_ACCPETED NUMERIC = NULL,
    @END_TASK BIT = NULL
AS
BEGIN
    BEGIN TRANSACTION
    IF @TASK_ID_ACCPETED IS NOT NULL AND @BY_USER_SESSION IS NOT NULL AND EXISTS(SELECT 1 FROM dbo.TASKS WHERE TASKS_ID = @TASK_ID_ACCPETED) AND NOT @END_TASK = 1
    BEGIN
        BEGIN TRY
            UPDATE dbo.TASKS
            SET ACCEPTED_BY_SYS_USER_ID = dbo.GET_USER_ID_BY_SESSION(@BY_USER_SESSION),
                START_DATE_TIME = CONVERT(NVARCHAR(19), GETDATE(), 120)
            WHERE TASKS_ID = @TASK_ID_ACCPETED
        END TRY
        BEGIN CATCH
            ROLLBACK;
        END CATCH
    END

    IF @END_TASK = 1
    BEGIN
        BEGIN TRY
            UPDATE dbo.TASKS
            SET END_DATE_TIME = CONVERT(NVARCHAR(19), GETDATE(), 120),
                ACTUAL_TIME_TASK_TOOK = (SELECT TOP 1 DATEDIFF(SECOND, CONVERT(DATETIME, START_DATE_TIME), CONVERT(DATETIME, CONVERT(NVARCHAR(19), GETDATE(), 120))) / 3600.0
                                         FROM dbo.TASKS WHERE TASKS_ID = @TASK_ID_ACCPETED)
            WHERE TASKS_ID = @TASK_ID_ACCPETED

            INSERT INTO dbo.WORK_HOUR_REPORT_LOG (SYS_USER_ID, COMPLETED_TASK_ID)
            VALUES ((SELECT TOP 1 SYS_USER_ID FROM dbo.SYS_USERS WHERE LOGIN_SESSION = @BY_USER_SESSION), @TASK_ID_ACCPETED)
        END TRY
        BEGIN CATCH
            ROLLBACK;
        END CATCH
    END

    SELECT
        TASKS_ID,
        TASK_NAME,
        TASK_DESCRIPTION,
        CASE WHEN START_DATE_TIME IS NULL THEN N'No one has accepted this task yet' ELSE START_DATE_TIME END AS START_DATE_TIME,
        CASE WHEN START_DATE_TIME IS NULL THEN N'No one has finished this task yet' ELSE END_DATE_TIME END AS END_DATE_TIME,
        EST_HOURS_IT_WILL_TAKE,
        HOURLY_RATE_FOR_TASK,
        SU.USERNAME AS TASK_CREATED_BY
    FROM dbo.TASKS T
    INNER JOIN dbo.SYS_USERS SU ON SU.SYS_USER_ID = T.TASK_CREATED_BY_SYS_USER_ID
    COMMIT
END
GO

-- 21. UPDATING_LIST_OF_SYS_OBJECTS
CREATE PROCEDURE dbo.UPDATING_LIST_OF_SYS_OBJECTS
    @SYS_OBJECT_NAME NVARCHAR(100),
    @SYS_OBJECT_CODE NUMERIC
AS
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo.SYS_OBJECTS WHERE SYS_OBJECT_NAME = @SYS_OBJECT_NAME AND SYS_OBJECT_CODE = @SYS_OBJECT_CODE)
    BEGIN
        INSERT INTO dbo.SYS_OBJECTS (SYS_OBJECT_NAME, SYS_OBJECT_CODE) VALUES (@SYS_OBJECT_NAME, @SYS_OBJECT_CODE)
        SELECT N'CREATED NEW SYS OBJECT' AS STATUS
    END
    ELSE
    BEGIN
        SELECT N'SYS OBJECT FOUND' AS STATUS
    END
END
GO

-- 22. WORK_HOUR_REPORT
CREATE PROCEDURE dbo.WORK_HOUR_REPORT
    @LOGIN_SESSION NVARCHAR(512)
AS
BEGIN
    SELECT
        WHRL.WORK_HOUR_REPORT_LOG_ID,
        SU.USERNAME,
        TASK_NAME,
        TASK_DESCRIPTION,
        START_DATE_TIME,
        END_DATE_TIME,
        EST_HOURS_IT_WILL_TAKE,
        ACTUAL_TIME_TASK_TOOK,
        HOURLY_RATE_FOR_TASK,
        CAST((HOURLY_RATE_FOR_TASK * ACTUAL_TIME_TASK_TOOK) AS money) AS MONEY_MADE,
        SU.BASE_SALARY
    FROM dbo.WORK_HOUR_REPORT_LOG WHRL
    INNER JOIN dbo.SYS_USERS SU ON WHRL.SYS_USER_ID = SU.SYS_USER_ID
    INNER JOIN dbo.TASKS T ON T.TASKS_ID = WHRL.COMPLETED_TASK_ID
    WHERE SU.LOGIN_SESSION = @LOGIN_SESSION AND END_DATE_TIME IS NOT NULL
    ORDER BY END_DATE_TIME DESC
END
GO

-- =====================================================================
-- Final message
-- =====================================================================
PRINT 'PROJECT_ZERO database and all objects created successfully.';
GO