package IFMS;

public enum selectQueries {
    
    inventoryLocationsReadable("SELECT il.INVENTORY_LOCATION_ID, il.INVENTORY_LOCATION_NAME, " +
        "il.INVENTORY_LOCATION_ADDRESS, il.INVENTORY_LOCATION_LAT, " +
        "il.INVENTORY_LOCATION_LONG, lilt.INVENTORY_LOCATION_TYPE_TITLE " +
        "FROM INVENTORY_LOCATION il " +
        "INNER JOIN LT_INVENTORY_LOCATION_TYPE lilt " +
        "ON il.LT_INVENTORY_LOCATION_TYPE_ID = lilt.LT_INVENTORY_LOCATION_TYPE_ID " +
        "WHERE ISNULL(IL.IS_DELETED,0) = 0 AND ? IS NOT NULL"
    ),
    selectUserLoginLog(
        "SELECT USER_LOGIN_LOG_ID, USERNAME, LOGIN_DATE " +
        "FROM LOGIN_LOG_SELECT(?) " +
        "ORDER BY USER_LOGIN_LOG_ID DESC"
    ),
    selectUserRolesLog(
        "SELECT USERS_ROLES_ID, ROLES_TITLE, ASSIGNMENT_DATE " +
        "FROM ROLES_LOG_SELECT(?) " +
        "ORDER BY USERS_ROLES_ID DESC"
    ),
    userList(
        "SELECT SU.SYS_USER_ID, SU.USERNAME, SU.BASE_SALARY " +
        "FROM SYS_USERS SU"
    ),
    usersRoleList(
        "SELECT SU.SYS_USER_ID, SU.USERNAME, LR.ROLES_TITLE " +
        "FROM SYS_USERS SU " +
        "LEFT JOIN USERS_ROLES UR ON SU.SYS_USER_ID = UR.SYS_USER_ID AND COALESCE(UR.IS_ACTIVE, 1) = 1 " +
        "LEFT JOIN LT_ROLES LR ON LR.ROLE_CODE = UR.ROLE_CODE " +
        "WHERE ? IS NOT NULL"
    ),
    roleList(
        "SELECT ROLE_CODE, ROLES_TITLE FROM LT_ROLES WHERE ? IS NOT NULL"
    ),
    rolesAndPermissionsList(
        "SELECT LR.ROLES_ID AS ID, LR.ROLE_CODE AS roleCode, LR.ROLES_TITLE AS permissionTitle, " +
        "SO.SYS_OBJECT_NAME AS featurePermission, SCA.CAN_READ AS canRead, SCA.CAN_WRITE AS canWrite " +
        "FROM LT_ROLES LR " +
        "LEFT JOIN SYS_CALL_ACCESS SCA ON LR.ROLE_CODE = SCA.ROLE_CODE " +
        "LEFT JOIN SYS_OBJECTS SO ON SCA.SYS_OBJECT_CODE = SO.SYS_OBJECT_CODE " +
        "WHERE ? IS NOT NULL " +
        "ORDER BY LR.ROLE_CODE ASC"
    ),
    featuresList(
        "SELECT SYS_OBJECT_CODE AS featuresCode, SYS_OBJECT_NAME AS featuresName " +
        "FROM SYS_OBJECTS WHERE ? IS NOT NULL"
    ),
    productsCount(
        "SELECT COUNT(p.PRODUCTS_ID) AS COUNT FROM PRODUCTS p " +
        "WHERE IS_DELETED = 0 AND ? IS NOT NULL"
    ),
    productsCategoryCount(
        "SELECT COUNT(PRODUCTS_CATEGORY_ID) AS COUNT FROM PRODUCTS_CATEGORY " +
        "WHERE IS_DELETED = 0 AND ? IS NOT NULL"
    ),
    inventoryLocationCount(
        "SELECT COUNT(*) AS COUNT FROM INVENTORY_LOCATION il " +
        "WHERE IS_DELETED = 0 AND ? IS NOT NULL"
    ),
    activeMovementsCount(
        "SELECT COUNT(*) AS COUNT FROM PRODUCTS_MOVEMENTS pm " +
        "WHERE IS_DELETED = 0 AND pm.IS_ACTIVE = 1 AND ? IS NOT NULL"
    ),
    allMovementsCount(
        "SELECT COUNT(*) AS COUNT FROM PRODUCTS_MOVEMENTS WHERE ? IS NOT NULL"
    ),
    lowStockProducts(
        "SELECT ps.PRODUCTS_STOCKS_ID, p.PRODUCTS_NAME, il.INVENTORY_LOCATION_NAME, " +
        "ps.PRODUCT_COUNT_IN_STOCK " +
        "FROM PRODUCTS_STOCKS ps " +
        "INNER JOIN PRODUCTS p ON ps.PRODUCTS_ID = p.PRODUCTS_ID " +
        "INNER JOIN INVENTORY_LOCATION il ON ps.INVENTORY_LOCATION_ID = il.INVENTORY_LOCATION_ID " +
        "WHERE ps.PRODUCT_COUNT_IN_STOCK < 5 AND ? IS NOT NULL"
    ),
    productsCategoryList(
        "SELECT pc.PRODUCTS_CATEGORY_ID, pc.PRODUCTS_CATEGORY_NAME " +
        "FROM PRODUCTS_CATEGORY pc WHERE IS_DELETED = 0 AND ? IS NOT NULL"
    ),
    productsWithCategory(
        "SELECT p.PRODUCTS_ID, p.PRODUCTS_NAME, pc.PRODUCTS_CATEGORY_NAME " +
        "FROM PRODUCTS p " +
        "INNER JOIN PRODUCTS_CATEGORY pc ON pc.PRODUCTS_CATEGORY_ID = p.PRODUCTS_CATEGORY_ID " +
        "WHERE p.IS_DELETED = 0 AND ? IS NOT NULL"
    ),
    driversList(
        "SELECT DRIVER_ID, CONCAT(DRIVER_NAME,N' ', d.DRIVER_LAST_NAME) AS DRIVER_FULL_NAME, " +
        "d.DRIVERS_NATIONAL_CODE, d.DRIVERS_PHONE_NUMBER " +
        "FROM DRIVERS d " +
        "WHERE ISNULL(d.IS_DELETED, 0) = 0 AND ? IS NOT NULL"
    ),
    fleetTeamList(
        "SELECT FLEET_TEAM_ID, ft.FLEET_TEAM_NAME, ft.DESCRIPTION " +
        "FROM FLEET_TEAMS ft " +
        "WHERE ISNULL(IS_DELETED, 0) = 0 AND ? IS NOT NULL"
    ),
    inventoryLocationsWithType(
        "SELECT il.INVENTORY_LOCATION_ID, il.INVENTORY_LOCATION_NAME, " +
        "il.INVENTORY_LOCATION_ADDRESS, il.INVENTORY_LOCATION_LAT, il.INVENTORY_LOCATION_LONG, " +
        "LILT.INVENTORY_LOCATION_TYPE_TITLE " +
        "FROM INVENTORY_LOCATION il " +
        "INNER JOIN LT_INVENTORY_LOCATION_TYPE lilt " +
        "ON il.LT_INVENTORY_LOCATION_TYPE_ID = lilt.LT_INVENTORY_LOCATION_TYPE_ID " +
        "AND lilt.IS_DELETED = 0 " +
        "WHERE ISNULL(il.IS_DELETED, 0) = 0 AND ? IS NOT NULL"
    ),
    inventoryStockRequests(
        "SELECT isr.INVENTORY_STOCK_REQUEST_ID, " +
        "il.INVENTORY_LOCATION_NAME AS REQUESTING_INVENTORY, " +
        "il2.INVENTORY_LOCATION_NAME AS SUPPLYING_INVENTORY, " +
        "p.PRODUCTS_ID, p.PRODUCTS_NAME, isr.PRODUCTS_COUNT, " +
        "CASE WHEN isr.DRIVER_ID_ASSIGNED IS NOT NULL THEN 1 ELSE 0 END AS IS_ACCEPTED_BY_FLEET " +
        "FROM INVENTORY_STOCK_REQUEST isr " +
        "LEFT JOIN PRODUCTS p ON p.PRODUCTS_ID = isr.PRODUCTS_ID " +
        "LEFT JOIN INVENTORY_LOCATION il ON il.INVENTORY_LOCATION_ID = isr.INVENTORY_ID " +
        "LEFT JOIN INVENTORY_LOCATION il2 ON il2.INVENTORY_LOCATION_ID = isr.FROM_INVENTORY_ID " +
        "WHERE ISNULL(il.IS_DELETED,0) = 0 AND ? IS NOT NULL"
    ),
    driversWithTeam(
        "SELECT d.DRIVER_ID, CONCAT(N' ',d.DRIVER_NAME,N' ', d.DRIVER_LAST_NAME, N' ') AS DRIVER_FULL_NAME, " +
        "d.DRIVERS_NATIONAL_CODE, ft.FLEET_TEAM_NAME " +
        "FROM DRIVERS d " +
        "LEFT JOIN FLEET_TEAMS ft ON d.FLEET_TEAM_ID = ft.FLEET_TEAM_ID " +
        "WHERE ISNULL(d.IS_DELETED,0)=0 AND ? IS NOT NULL"
    ),
    inventoryLocationTypes(
        "SELECT LT_INVENTORY_LOCATION_TYPE_ID, INVENTORY_LOCATION_TYPE_TITLE " +
        "FROM LT_INVENTORY_LOCATION_TYPE " +
        "WHERE ISNULL(IS_DELETED,0) = 0 AND ? IS NOT NULL"
    ),
    tasksReport(
        "EXEC TASKS_REPORT ?"
    ),
    workHourReport(
        "EXEC WORK_HOUR_REPORT ?"
    ),
    auditLog(
        "EXEC ACTIVITY_LOG_MANAGER @LOGGIN_SESSION=?, @READ_ONLY=1, @ACTIVITY_REMARK=N''"
    );
    
    private final String query;
    
    selectQueries(String query)
    {
        this.query = query;
    }
    
    
    public String sql(){return this.query;}
}
